// constants/theme.ts
// armandotfit theme — "SIGNAL" (see docs/architecture/signal-thesis.md).
//
// A two-register instrument system on the shell's `ink` dialect (flat
// atmosphere, chit toasts, curtain transitions — see DIALECT below):
//
//   • The DESK (light default, dark opt-in) — cold steel surfaces,
//     near-black ink, hairline borders, no shadows. Reading surfaces
//     that never shout.
//   • The FLOOR (colors.focus.*) — the live-session register:
//     mode-independent near-black, one family for the stage, the armed
//     set, and every surface that must read like an instrument instead
//     of a document.
//
// One SIGNAL color (the `brand` slot) marks THE action per screen and
// nothing else. Every text-bearing slot is measured WCAG AA on the
// darkest surface it rides (the full matrix lives in the thesis §3.3
// and is regenerated by the contrast probe before any palette commit):
// light signal #E8510A (3.74:1 as fill on card), signalText #993A05
// (7.09:1), ink textOnBrand on the fill (5.17:1); dark signal #FF7A29
// (6.62:1 on card), signalText #FF8B47 (7.41:1), ink-on-signal 7.47:1;
// focus text #F2F5FA on #0A0C10 (17.91:1).
//
// Structure + axes (dialect/shapes/fonts/typography/atmosphere/drawer/
// toast/transition + the TypeFaces width axis + the focus register) are
// the shell's, synced from arqavellum. Only the palette values and the
// DIALECT pick are armandotfit's own.

import type { TextStyle } from 'react-native';

// TextStyle-shaped typography tokens. Typing these explicitly avoids the
// `fontWeight: string` widening that breaks spread-into-<Text> calls
// (RN's TextStyle.fontWeight is a union of string literals, not `string`).
type TypographyToken = Pick<
  TextStyle,
  | 'fontSize'
  | 'fontWeight'
  | 'lineHeight'
  | 'letterSpacing'
  | 'fontFamily'
  | 'fontVariant'
>;

// ── Type families ───────────────────────────────────────────────────────
// The optional display pair, hoisted so typography tokens can reference
// it inside the same object literal. A consumer whose design language is
// printed matter declares a display face (poster titles, hero figures,
// totals) and/or a mono face (every figure that reads as ledger output —
// prices, stock, dates, metrics, eyebrows); body/UI text stays the
// platform sans for legibility. All default to undefined — the starter
// renders the platform sans everywhere, and every read below is a no-op
// until a consumer fills them, so declaring the axis never moves the
// default look.
//
// Self-hosting recipe (web): OFL/compatible files in `public/fonts/`
// (woff2 first, TTF fallback), the @font-face block in an id'd <style>
// in `index.html`, restored at runtime from `app/_layout.tsx` (static
// export strips <head> styles), plus <link rel="preload" as="font"
// crossorigin> lines — the build-time injector copies both into every
// exported route. Native extension: load the same files through
// expo-font instead of the <style> block.
export interface TypeFaces {
  /** Display face — poster titles, display figures, totals. */
  display?: string;
  /**
   * Condensed position of the display face — for consumers whose
   * display face carries a width axis. Declared as a second
   * @font-face over the SAME variable file with `font-stretch` pinned
   * (see index.html): one download, two families, and RN code never
   * touches fontStretch (which RN's TextStyle does not carry).
   */
  displayCondensed?: string;
  /** Mono face — ledger figures: prices, stock, dates, metrics, eyebrows. */
  mono?: string;
}

const FONTS = {
  // The SIGNAL pair (docs/architecture/signal-thesis.md §2.1). Saira
  // ships as one variable woff2 covering wght 100–900 × wdth 75–125;
  // 'Saira Cond' is the same file pinned to wdth 75 via a second
  // @font-face. Martian Mono is one variable woff2 (wght 100–800).
  // Files in public/fonts/, @font-face + preloads in index.html (id'd
  // style), runtime restore in app/_layout.tsx — the injector carries
  // both into every exported route.
  display: 'Saira',
  displayCondensed: 'Saira Cond',
  mono: 'Martian Mono',
} as TypeFaces;

// ── Design dialect ──────────────────────────────────────────────────────
// The ONE family declaration. A consumer's design language is not four
// independent flags that must agree by convention — it is one dialect
// that presets every surface-language point below (atmosphere, drawer,
// toast, transition). Sub-points remain as explicit overrides: writing a
// literal `style` on any of them beats the preset, for consumers whose
// taste mixes deliberately.
//   • 'glass' (default) — the starter's own look: drifting aurora orbs,
//     the glass-scrim sheet drawer, the bordered-card toast, no route
//     transition.
//   • 'ink' — flat air (no orbs), the InkPanel drawer, the ink chit
//     toast, and the ink route curtain. The curtain is
//     consumer-implemented machinery that READS the transition axis
//     below — the shell ships no transition primitive of its own (a
//     future one would read the same declaration).
const DIALECT = 'ink' as 'glass' | 'ink';
const DIALECT_PRESETS = {
  glass: { atmosphere: 'aurora', drawer: 'sheet', toast: 'card', transition: 'none' },
  ink: { atmosphere: 'flat', drawer: 'ink', toast: 'chit', transition: 'curtain' },
} as const;

// The focus register — the Floor. Identical values in both palettes BY
// DESIGN: the live-session stage does not follow the Desk's mode. It is
// a surface family (like `glass` / `mobilePremium`), not a third color
// scheme — `useAppTheme()` still resolves exactly two.
const FOCUS_REGISTER = {
  background: '#0A0C10',
  surface: '#12151C',
  surfaceAlt: '#181D27',
  border: '#232B3A',
  text: '#F2F5FA',
  muted: '#98A2B4',
  signal: '#FF7A29',
  onSignal: '#0A0C10',
  track: '#1E2430',
  signalSoft: 'rgba(255, 122, 41, 0.16)',
} as const;

export const theme = {
  colors: {
    // ── Light surface (the Desk, default) ─────────────────────────────
    // Cold steel: light grays with a deliberate blue cast, near-black
    // ink, hairline borders. Every MobilePremium primitive defaults to
    // this palette unless the consumer flips `colorScheme` to 'dark'.
    light: {
      // UI element colors
      background: '#F4F5F8',
      backgroundAlt: '#ECEEF2',
      card: '#FFFFFF',
      cardAlt: '#F1F3F6',
      border: '#D3D8E0',

      // Card border colors — 1px precision edges on light steel.
      cardBorder: 'rgba(11, 14, 19, 0.10)',
      cardBorderHover: 'rgba(11, 14, 19, 0.18)',

      // Text colors. Every informative slot clears WCAG AA (4.5:1) on
      // the DARKEST light surface it rides (page #E8EAEE). The ladder:
      // text (19.33 on card) → textSecondary (10.31) → textMuted (4.97
      // on page) → tertiary (decorative only, see below).
      text: '#0B0E13',
      textMuted: '#5B6472',
      textSecondary: '#39414D',

      // Interactive element colors — the `brand` slot: the SIGNAL.
      // One hue, measured at both jobs: as a fill/large-type slot it
      // clears 3:1 (#E8510A = 3.74 on card); as small text it never
      // appears — `brandText` below is the text companion.
      brand: '#E8510A',
      brandHover: '#D64A08',
      brandPress: '#C44307',
      brandMuted: 'rgba(232, 81, 10, 0.08)',
      brandSoft: 'rgba(232, 81, 10, 0.12)',
      buttonBackground: '#E8510A',
      buttonBackgroundDisabled: 'rgba(232, 81, 10, 0.5)',

      // The brand slot's TEXT companion — the same hue darkened until
      // it clears WCAG AA (4.5:1) as small text (labels, eyebrows,
      // links) on the steel surfaces: 7.09:1 on card, 5.89:1 on page.
      brandText: '#993A05',

      // Brand-hue accent for inverted plates (the chit, the curtain,
      // the swap bench). Light mode's plate is the focus register — a
      // brightened ember reads on it (8.4:1 on #0A0C10).
      brandOnInk: '#FF8B47',

      // Semantic status colors. Measured AA as TEXT on card AND page:
      // success 6.06/5.03, warning 5.73/4.76, error 6.39/5.31, info
      // 5.74/4.76.
      status: {
        success: '#0B7147',
        warning: '#8F5B05',
        error: '#B52727',
        info: '#1D5FD6',
      },

      // Re-export aliases for call sites that read `success` and `alert`
      // at the top level (alternative to `status.success` / `status.error`).
      success: '#0B7147',
      alert: '#B52727',

      // Text color for content rendered on top of the brand color slot
      // (button labels, the selected check). Road-sign discipline: ink
      // on signal — white on this orange measured 2.60:1 and is banned.
      textOnBrand: '#0B0E13',

      // Secondary text on brand surfaces (helper lines, chip sublabels).
      // Ink at 0.8 alpha — hierarchy against `textOnBrand` while the
      // composite still clears AA on the fill.
      textOnBrandMuted: 'rgba(11, 14, 19, 0.8)',

      // Deeper background for full-bleed screens — the Desk's page
      // tone: concrete-steel, never warm.
      backgroundDeep: '#E8EAEE',

      // Text color variants. `textColors.muted` and `textMuted` are
      // unified (same value, both names). `tertiary` is DECORATIVE ONLY
      // (3.09:1 on card): placeholders, disabled states, watermarks —
      // it never carries information; informative quiet text reads
      // `textMuted`.
      textColors: {
        muted: '#5B6472',
        secondary: '#39414D',
        tertiary: '#8B93A1',
      },

      // Icon background tints (semantic — darker hue on pale tint).
      iconBackground: {
        blue: 'rgba(29, 95, 214, 0.10)',
        green: 'rgba(11, 113, 71, 0.10)',
        purple: 'rgba(126, 34, 206, 0.10)',
        orange: 'rgba(232, 81, 10, 0.10)',
        white: 'rgba(11, 14, 19, 0.06)',
      },

      // Glass tokens (kept for the shell's glass-dialect primitives).
      // On the Desk these read as steel tints, not frosted windows.
      glass: {
        background: 'rgba(255, 255, 255, 0.72)',
        backgroundLight: 'rgba(255, 255, 255, 0.55)',
        border: 'rgba(11, 14, 19, 0.10)',
        borderHighlight: 'rgba(11, 14, 19, 0.18)',
        borderHover: 'rgba(11, 14, 19, 0.14)',
        emptyInputBorder: 'rgba(11, 14, 19, 0.22)',
        panelBackground: 'rgba(255, 255, 255, 0.6)',
        inputBackground: 'rgba(11, 14, 19, 0.04)',
        inputFocusBackground: 'rgba(232, 81, 10, 0.06)',
      },

      // Alert background tint for error containers.
      alertBackground: 'rgba(181, 39, 39, 0.08)',

      // ── Mobile premium primitive kit tokens ───────────────────────────
      // The Desk is FLAT: hairlines and tint steps declare elevation,
      // not glow. The one shadow in the system lives on the armed slab
      // (see focus usage in composed components).
      mobilePremium: {
        // Hairline border (inner) — dark-on-light at low opacity.
        hairlineBorder: 'rgba(11, 14, 19, 0.10)',
        hairlineBorderStrong: 'rgba(11, 14, 19, 0.20)',

        // Surface gradient stops — the Desk runs flat; the gradient is
        // a whisper, kept for primitives that composite it.
        surfaceGradientTop: 'rgba(11, 14, 19, 0.02)',
        surfaceGradientBottom: 'rgba(11, 14, 19, 0.0)',

        // Contact shadow — a 1px seat, not a glow.
        surfaceGlow: '0 1px 2px rgba(11, 14, 19, 0.05)',

        // Backdrop blur for web (saturate is safe on light surfaces).
        surfaceBackdropBlur: 'blur(24px) satur(160%)',

        // Android Chrome fallback — near-solid surface + milder blur.
        androidChromeSurfaceBackground: 'rgba(255, 255, 255, 0.88)',
        androidChromeSurfaceBlur: 'blur(12px)',

        // Nav drawer (shell parity; the drawer is retired from this
        // app's chrome but the primitive stays synced).
        navScrimBackdropBlur: 'blur(8px)',
        navScrimAlpha: 'dd',
        navPanelShadow: '4px 0 32px rgba(0, 0, 0, 0.36), 0 2px 8px rgba(0, 0, 0, 0.2)',

        // Faint vignette to settle the page into its edges (web).
        atmosphereVignette: 'inset 0 0 160px 60px rgba(11, 14, 19, 0.03)',

        // Rail (progress) — fill travels across a 2px track.
        railTrack: 'rgba(11, 14, 19, 0.10)',
        railFillShadow: 'none',
      },

      // ── The focus register (the Floor) ────────────────────────────────
      // Mode-independent by design: the stage renders the same family
      // whether the Desk runs light or dark. Measured: text 17.91 on
      // background / 16.71 on surface; muted 7.61; signal-as-fill 7.52;
      // onSignal 7.52. See thesis §3.
      focus: FOCUS_REGISTER,
    },

    // ── Dark surface (the Desk at night, opt-in) ───────────────────────
    // Mirror of `light` with every key retuned for dark surfaces: cold
    // graphite, never slate-blue at the deep end. The structural shape
    // MUST match `light` so `theme.colors[colorScheme].*` is type-safe.
    dark: {
      background: '#10131A',
      backgroundAlt: '#141822',
      card: '#161B26',
      cardAlt: '#1C2230',
      border: '#2A3140',

      // Card border colors — light-on-dark hairlines.
      cardBorder: 'rgba(242, 245, 250, 0.10)',
      cardBorderHover: 'rgba(242, 245, 250, 0.18)',

      // Text colors — measured: text 15.08 on card, secondary 10.45,
      // muted 5.70 (6.43 on page, 5.26 on cardAlt).
      text: '#EDF0F5',
      textMuted: '#8B95A6',
      textSecondary: '#C3CAD6',

      // The `brand` slot at night: a brighter signal — 6.62:1 on card
      // as fill/large type; `brandText` carries small text at 7.41:1.
      brand: '#FF7A29',
      brandHover: '#FF8B47',
      brandPress: '#F06E1D',
      brandMuted: 'rgba(255, 122, 41, 0.14)',
      brandSoft: 'rgba(255, 122, 41, 0.18)',
      buttonBackground: '#FF7A29',
      buttonBackgroundDisabled: 'rgba(255, 122, 41, 0.4)',

      // Text companion of `brand` (see `light.brandText`).
      brandText: '#FF8B47',

      // Brand-hue accent for inverted plates. Dark mode's chit/curtain
      // ride the focus register too; a deepened signal reads on ice.
      brandOnInk: '#B23A08',

      // Semantic status colors — brightened for dark contrast (all
      // 6.4–10.4:1 as text on card and page).
      status: {
        success: '#3DD68C',
        warning: '#E8B44A',
        error: '#F27B7B',
        info: '#6CA6FF',
      },

      // Aliases matching `light` (kept in sync across both palettes).
      success: '#3DD68C',
      alert: '#F27B7B',

      // Ink on signal — the road-sign rule holds at night.
      textOnBrand: '#0B0D12',

      // Secondary text on brand — ink alpha over the bright fill.
      textOnBrandMuted: 'rgba(11, 13, 18, 0.8)',

      // Page tone for full-bleed screens — cold near-black.
      backgroundDeep: '#0B0D12',

      // Text color variants. `tertiary` is DECORATIVE ONLY (3.61 on
      // card) — never carries information.
      textColors: {
        muted: '#8B95A6',
        secondary: '#C3CAD6',
        tertiary: '#697386',
      },

      // Icon background tints — bright hue on dark tint.
      iconBackground: {
        blue: 'rgba(108, 166, 255, 0.16)',
        green: 'rgba(61, 214, 140, 0.16)',
        purple: 'rgba(192, 132, 252, 0.16)',
        orange: 'rgba(255, 122, 41, 0.16)',
        white: 'rgba(242, 245, 250, 0.08)',
      },

      // Glassmorphism (dark) — smoked steel tints.
      glass: {
        background: 'rgba(20, 24, 34, 0.72)',
        backgroundLight: 'rgba(20, 24, 34, 0.55)',
        border: 'rgba(242, 245, 250, 0.10)',
        borderHighlight: 'rgba(242, 245, 250, 0.20)',
        borderHover: 'rgba(242, 245, 250, 0.14)',
        emptyInputBorder: 'rgba(242, 245, 250, 0.22)',
        panelBackground: 'rgba(11, 13, 18, 0.6)',
        inputBackground: 'rgba(242, 245, 250, 0.05)',
        inputFocusBackground: 'rgba(255, 122, 41, 0.10)',
      },

      // Alert background tint for error containers (dark red wash).
      alertBackground: 'rgba(242, 123, 123, 0.12)',

      // ── Mobile premium primitive kit tokens (dark) ───────────────────
      // Flat at night too: hairlines up, shadows down to a seat.
      mobilePremium: {
        hairlineBorder: 'rgba(242, 245, 250, 0.10)',
        hairlineBorderStrong: 'rgba(242, 245, 250, 0.20)',

        surfaceGradientTop: 'rgba(242, 245, 250, 0.03)',
        surfaceGradientBottom: 'rgba(242, 245, 250, 0.0)',

        surfaceGlow: '0 1px 2px rgba(0, 0, 0, 0.4)',

        surfaceBackdropBlur: 'blur(24px) satur(140%)',

        androidChromeSurfaceBackground: 'rgba(16, 19, 26, 0.88)',
        androidChromeSurfaceBlur: 'blur(12px)',

        navScrimBackdropBlur: 'blur(8px)',
        navScrimAlpha: 'cc',
        navPanelShadow: '4px 0 32px rgba(0, 0, 0, 0.36), 0 2px 8px rgba(0, 0, 0, 0.2)',

        atmosphereVignette: 'inset 0 0 160px 60px rgba(0, 0, 0, 0.28)',

        railTrack: 'rgba(242, 245, 250, 0.12)',
        railFillShadow: 'none',
      },

      // ── The focus register (identical to light — see above) ──────────
      focus: FOCUS_REGISTER,
    },
  },

  // Spacing system
  spacing: {
    xxs: 2,
    xs: 4,
    small: 8,
    medium: 16,
    large: 24,
    xlarge: 32,
    xxlarge: 48,
  },

  // Font sizes
  fontSize: {
    xs: 12,
    small: 14,
    medium: 16,
    large: 18,
    xlarge: 24,
    xxlarge: 32,
  },

  // Border radius
  borderRadius: {
    small: 8,
    medium: 12,
    large: 16,
    pill: 9999,
  },

  // ── Shape tokens ────────────────────────────────────────────────────
  // Semantic corner radii for the MobilePremium kit. SIGNAL runs
  // machine-cut: surfaces slightly softened, controls crisp, chips
  // round (a pill marks metadata, never an action). `borderRadius`
  // above is the raw size scale for ad-hoc shapes; primitives use
  // these semantics.
  shapes: {
    /** Cards + section surfaces (MobileSurface, StatCard, alerts). */
    surface: 10,
    /** Portal panels — bottom sheets, calendar/dialog bodies. */
    sheet: 14,
    /** Inputs, buttons, selects — interactive controls. */
    control: 8,
    /** Small tiles — selection rows, option containers, thumbnails. */
    tile: 6,
    /** Chips, tags, badges. 999 renders full round. */
    tag: 999,
  },

  // ── Atmosphere tokens ────────────────────────────────────────────────
  // The atmosphere-language override point — the same discipline as
  // `shapes`: the consumer declares the background style ONCE here and
  // every MobileAtmosphere (scaffolds, drawers, auth screens) follows,
  // with no per-callsite prop threading. `MobileAtmosphere`'s
  // `showOrbs` prop remains as the explicit per-callsite override
  // (the dev showcase uses it to demo both styles under one theme).
  atmosphere: {
    /**
     * The background style the atmosphere renders.
     * - 'aurora': drifting color-field orbs over the base tint — the
     *   starter's premium read, the glass dialect's preset.
     * - 'flat': base tint + vignette only, no orbs — the instrument
     *   read for consumers whose design language wants calm steel.
     *   Orb drift stops too (nothing left to animate).
     *
     * Defaults to the dialect preset; write a literal to override.
     */
    style: DIALECT_PRESETS[DIALECT].atmosphere,
  },

  // ── Drawer tokens ────────────────────────────────────────────────────
  // The nav-drawer surface language override point — the same
  // discipline as `shapes`/`atmosphere`: declare it once here and the
  // drawer follows, no per-callsite props.
  //   • 'sheet': the glass-scrim iOS sheet this component shipped as —
  //     blur scrim, atmosphere body, hairline edge (the glass dialect's
  //     preset).
  //   • 'ink': the inverted plate (InkPanel) — text-color plate + brand
  //     edge rule, flat dim scrim (no blur), the masthead riding ON the
  //     plate (MobileHomeHeader onPlate). Defaults to the dialect
  //     preset; write a literal to override.
  drawer: {
    style: DIALECT_PRESETS[DIALECT].drawer,
  },

  // ── Toast tokens ────────────────────────────────────────────────────
  // The transient-message surface language, same discipline as the
  // family above. 'card' is the bordered card with colored icons — the
  // glass dialect's default. 'chit' is the instrument treatment: the
  // focus-register plate (near-black in both modes), ice type, one 7px
  // status dot, mono message when `fonts.mono` is declared, flat air
  // (no shadow, no stripe, no icon triad). Defaults to the dialect
  // preset; write a literal to override.
  toast: {
    style: DIALECT_PRESETS[DIALECT].toast,
  },

  // ── Transition tokens ────────────────────────────────────────────────
  // The route-transition axis — the one motion declaration. 'none' (the
  // glass dialect's preset): the curtain machinery stays retired —
  // withRouteCurtain passes straight through and the overlay never
  // mounts. 'curtain' (the ink preset): the shell's RouteCurtain plays
  // — the signal sweep (focus-page cover, 2px signal leading edge,
  // destination title stamped in the condensed face), wired through
  // NavigationHelper. Write a literal to override the preset.
  transition: {
    style: DIALECT_PRESETS[DIALECT].transition,
  },

  // ── Type families ───────────────────────────────────────────────────
  // The same discipline as shapes/atmosphere/drawer: declare the pair
  // ONCE here and every face-aware read (typography tokens, eyebrows,
  // figure styles) follows — no per-callsite fontFamily threading. See
  // the TypeFaces block above for the self-hosting recipe.
  fonts: FONTS,

  // ── Named type styles ─────────────────────────────────────────────────
  // The SIGNAL scale (docs/architecture/signal-thesis.md §2.2): two
  // interleaved ramps — words (11·13·15·16·18·30) and figures
  // (30·56·80, always condensed + tabular) — so a number is always one
  // register louder than the words around it. Line-heights snap to 2;
  // tracking goes slightly negative as size grows, positive at tracked
  // mono caps. Consumers import the named style and spread it; they do
  // NOT pick ad-hoc fontSize/fontWeight values. Retune the values
  // here, but keep the named-style discipline.
  typography: {
    mobileTitle: {
      fontSize: 30,
      fontWeight: '700',
      lineHeight: 34,
      letterSpacing: -0.5,
      fontFamily: FONTS.display,
    } satisfies TypographyToken,
    mobileSubtitle: {
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 22,
      letterSpacing: 0,
      fontFamily: FONTS.display,
    } satisfies TypographyToken,
    mobileBody: {
      fontSize: 15,
      fontWeight: '400',
      lineHeight: 22,
      letterSpacing: 0,
    } satisfies TypographyToken,
    mobileAction: {
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 20,
      letterSpacing: 0.1,
      fontFamily: FONTS.display,
    } satisfies TypographyToken,
    mobileEyebrow: {
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 14,
      letterSpacing: 1.2,
      fontFamily: FONTS.mono,
    } satisfies TypographyToken,
    mobileFieldLabel: {
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 16,
      letterSpacing: 0.1,
    } satisfies TypographyToken,
    // ── Figure language ────────────────────────────────────────────────
    // Numbers are the app's content, so the scale names their slots
    // too. Every figure token carries tabular figures by construction
    // — a call site cannot forget them — and rides the CONDENSED
    // display position: a stadium-clock read that fits three-digit
    // weights and 00:42 timers with room for the unit.
    mobileHero: {
      fontSize: 80,
      fontWeight: '800',
      lineHeight: 84,
      letterSpacing: -1,
      fontVariant: ['tabular-nums'],
      fontFamily: FONTS.displayCondensed,
    } satisfies TypographyToken,
    mobileDisplay: {
      fontSize: 56,
      fontWeight: '800',
      lineHeight: 60,
      letterSpacing: -0.5,
      fontVariant: ['tabular-nums'],
      fontFamily: FONTS.displayCondensed,
    } satisfies TypographyToken,
    mobileFigure: {
      fontSize: 30,
      fontWeight: '800',
      lineHeight: 34,
      letterSpacing: -0.25,
      fontVariant: ['tabular-nums'],
      fontFamily: FONTS.displayCondensed,
    } satisfies TypographyToken,
    mobileItemTitle: {
      fontSize: 18,
      fontWeight: '700',
      lineHeight: 24,
      letterSpacing: -0.2,
      fontFamily: FONTS.display,
    } satisfies TypographyToken,
    // Condensed title — mobileTitle's job in the condensed display
    // position: focus-register screens whose headline is a NAME read
    // at arm's length (the stage's station name).
    mobileTitleCondensed: {
      fontSize: 34,
      fontWeight: '800',
      lineHeight: 38,
      letterSpacing: -0.5,
      fontFamily: FONTS.displayCondensed,
    } satisfies TypographyToken,
    mobileLedger: {
      fontSize: 15,
      fontWeight: '500',
      lineHeight: 20,
      letterSpacing: 0,
      fontVariant: ['tabular-nums'],
      fontFamily: FONTS.mono,
    } satisfies TypographyToken,
    mobileMeta: {
      fontSize: 13,
      fontWeight: '400',
      lineHeight: 18,
      letterSpacing: 0,
      fontVariant: ['tabular-nums'],
    } satisfies TypographyToken,
    mobileTag: {
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
      letterSpacing: 0.4,
      fontFamily: FONTS.mono,
    } satisfies TypographyToken,
  },
};

// The two color schemes arqavellum supports. `light` is the default. Type-wide
// so consumers can type their own APIs (`onChangeColorScheme(next: ColorScheme)`).
export type ColorScheme = 'light' | 'dark';

// The atmosphere background styles (`theme.atmosphere.style`). 'aurora' is
// the starter default; a consumer declares 'flat' to turn the orbs off
// app-wide in one place.
export type AtmosphereStyle = 'aurora' | 'flat';

// The toast surface styles (`theme.toast.style`) — the bordered card the
// glass dialect presets vs the floating instrument chit the ink dialect
// presets.
export type ToastStyle = 'card' | 'chit';

// Convenience aliases — the resolved palette shape for either mode. Both
// `light` and `dark` are structurally identical, so the union collapses to
// a single shape.
export type ColorPalette = typeof theme.colors.light;
