// shared/exercises/corePlates.ts
//
// THE CORE PLATES — generated by scripts/import-exercise-db.ts: core
// lifts matched to their free-exercise-db figures by exact (plural-
// tolerant) name match or the hand-reviewed alias table in the
// importer. Regenerate, never hand-edit. Plates reuse the imported
// figure files where the target was imported.
//
// Core entries plated: 83 of 97.

export const CORE_PLATES: Record<string, string> = {
  'incline-barbell-press': '/exercise-plates/barbell-incline-bench-press-medium-grip.jpg', // <- Barbell Incline Bench Press - Medium Grip
  'incline-dumbbell-fly': '/exercise-plates/incline-dumbbell-flyes.jpg', // <- Incline Dumbbell Flyes
  'machine-chest-fly': '/exercise-plates/butterfly.jpg', // <- Butterfly
  'machine-incline-press': '/exercise-plates/leverage-incline-chest-press.jpg', // <- Leverage Incline Chest Press
  'cable-overhead-tricep-extension': '/exercise-plates/triceps-overhead-extension-with-rope.jpg', // <- Triceps Overhead Extension with Rope
  'machine-dip': '/exercise-plates/dip-machine.jpg', // <- Dip Machine
  'dumbbell-curl': '/exercise-plates/dumbbell-bicep-curl.jpg', // <- Dumbbell Bicep Curl
  'cable-curl': '/exercise-plates/standing-biceps-cable-curl.jpg', // <- Standing Biceps Cable Curl
  'cable-lateral-raise': '/exercise-plates/cable-seated-lateral-raise.jpg', // <- Cable Seated Lateral Raise
  'face-pull': '/exercise-plates/face-pull.jpg', // <- Face Pull
  'shoulder-press': '/exercise-plates/machine-shoulder-military-press.jpg', // <- Machine Shoulder (Military) Press
  'dumbbell-overhead-press': '/exercise-plates/dumbbell-shoulder-press.jpg', // <- Dumbbell Shoulder Press
  'back-extension': '/exercise-plates/hyperextensions-back-extensions.jpg', // <- Hyperextensions (Back Extensions)
  'cable-row': '/exercise-plates/seated-cable-rows.jpg', // <- Seated Cable Rows
  'lat-pulldown': '/exercise-plates/wide-grip-lat-pulldown.jpg', // <- Wide-Grip Lat Pulldown
  'straight-arm-pulldown': '/exercise-plates/straight-arm-pulldown.jpg', // <- Straight-Arm Pulldown
  'machine-shrug': '/exercise-plates/leverage-shrug.jpg', // <- Leverage Shrug
  'dumbbell-shrug': '/exercise-plates/dumbbell-shrug.jpg', // <- Dumbbell Shrug
  'leg-press': '/exercise-plates/leg-press.jpg', // <- Leg Press
  'bulgarian-split-squat': '/exercise-plates/elevated-back-lunge.jpg', // <- Elevated Back Lunge
  'machine-leg-curl': '/exercise-plates/seated-leg-curl.jpg', // <- Seated Leg Curl
  'leg-press-calf-raise': '/exercise-plates/calf-press-on-the-leg-press-machine.jpg', // <- Calf Press On The Leg Press Machine
  'standing-machine-calf-raise': '/exercise-plates/smith-machine-calf-raise.jpg', // <- Smith Machine Calf Raise
  'leg-raise': '/exercise-plates/hanging-leg-raise.jpg', // <- Hanging Leg Raise
  'machine-ab-crunch': '/exercise-plates/ab-crunch-machine.jpg', // <- Ab Crunch Machine
  'hack-squat': '/exercise-plates/hack-squat.jpg', // <- Hack Squat
  'seated-calf-raise': '/exercise-plates/seated-calf-raise.jpg', // <- Seated Calf Raise
  'romanian-deadlift': '/exercise-plates/romanian-deadlift.jpg', // <- Romanian Deadlift
  'floor-leg-raise': '/exercise-plates/flat-bench-lying-leg-raise.jpg', // <- Flat Bench Lying Leg Raise
  'incline-dumbbell-press': '/exercise-plates/incline-dumbbell-press.jpg', // <- Incline Dumbbell Press
  'overhead-tricep-extension': '/exercise-plates/standing-dumbbell-triceps-extension.jpg', // <- Standing Dumbbell Triceps Extension
  'overhead-press': '/exercise-plates/standing-military-press.jpg', // <- Standing Military Press
  'lateral-raise': '/exercise-plates/side-lateral-raise.jpg', // <- Side Lateral Raise
  'lying-leg-curl': '/exercise-plates/lying-leg-curls.jpg', // <- Lying Leg Curls
  'pull-up': '/exercise-plates/pullups.jpg', // <- Pullups
  'cable-crunch': '/exercise-plates/cable-crunch.jpg', // <- Cable Crunch
  'walking-lunge': '/exercise-plates/barbell-walking-lunge.jpg', // <- Barbell Walking Lunge
  'dumbbell-pullover': '/exercise-plates/straight-arm-dumbbell-pullover.jpg', // <- Straight-Arm Dumbbell Pullover
  'bench-dip': '/exercise-plates/bench-dips.jpg', // <- Bench Dips
  'barbell-row': '/exercise-plates/bent-over-barbell-row.jpg', // <- Bent Over Barbell Row
  'barbell-back-squat': '/exercise-plates/barbell-squat.jpg', // <- Barbell Squat
  'dumbbell-goblet-squat': '/exercise-plates/goblet-squat.jpg', // <- Goblet Squat
  'bodyweight-squat': '/exercise-plates/bodyweight-squat.jpg', // <- Bodyweight Squat
  'barbell-standing-calf-raise': '/exercise-plates/standing-barbell-calf-raise.jpg', // <- Standing Barbell Calf Raise
  'dumbbell-standing-calf-raise': '/exercise-plates/standing-dumbbell-calf-raise.jpg', // <- Standing Dumbbell Calf Raise
  'dumbbell-romanian-deadlift': '/exercise-plates/stiff-legged-dumbbell-deadlift.jpg', // <- Stiff-Legged Dumbbell Deadlift
  'barbell-overhead-tricep-extension': '/exercise-plates/standing-overhead-barbell-triceps-extension.jpg', // <- Standing Overhead Barbell Triceps Extension
  'dumbbell-rear-delt-fly': '/exercise-plates/reverse-flyes.jpg', // <- Reverse Flyes
  'barbell-shrug': '/exercise-plates/barbell-shrug.jpg', // <- Barbell Shrug
  'cable-chest-fly': '/exercise-plates/flat-bench-cable-flyes.jpg', // <- Flat Bench Cable Flyes
  'floor-crunch': '/exercise-plates/crunches.jpg', // <- Crunches
  'barbell-curl': '/exercise-plates/barbell-curl.jpg', // <- Barbell Curl
  'barbell-split-squat': '/exercise-plates/split-squats.jpg', // <- Split Squats
  'pistol-squat': '/exercise-plates/one-leg-barbell-squat.jpg', // <- One Leg Barbell Squat
  'barbell-pullover': '/exercise-plates/bent-arm-barbell-pullover.jpg', // <- Bent-Arm Barbell Pullover
  'barbell-skull-crusher': '/exercise-plates/lying-triceps-press.jpg', // <- Lying Triceps Press
  'cable-tricep-pushdown': '/exercise-plates/triceps-pushdown.jpg', // <- Triceps Pushdown
  'one-arm-dumbbell-row': '/exercise-plates/one-arm-dumbbell-row.jpg', // <- One-Arm Dumbbell Row
  'inverted-row': '/exercise-plates/inverted-row.jpg', // <- Inverted Row
  'wide-grip-cable-row': '/exercise-plates/seated-cable-rows.jpg', // <- Seated Cable Rows
  'chest-supported-dumbbell-row': '/exercise-plates/dumbbell-incline-row.jpg', // <- Dumbbell Incline Row
  'ez-bar-curl': '/exercise-plates/ez-bar-curl.jpg', // <- EZ-Bar Curl
  'flat-barbell-bench-press': '/exercise-plates/barbell-bench-press-medium-grip.jpg', // <- Barbell Bench Press - Medium Grip
  'flat-dumbbell-bench-press': '/exercise-plates/dumbbell-bench-press.jpg', // <- Dumbbell Bench Press
  'machine-chest-press': '/exercise-plates/leverage-chest-press.jpg', // <- Leverage Chest Press
  't-bar-row': '/exercise-plates/t-bar-row-with-handle.jpg', // <- T-Bar Row with Handle
  'machine-seated-row': '/exercise-plates/leverage-iso-row.jpg', // <- Leverage Iso Row
  'chin-up': '/exercise-plates/chin-up.jpg', // <- Chin-Up
  'arnold-press': '/exercise-plates/arnold-dumbbell-press.jpg', // <- Arnold Dumbbell Press
  'hammer-curl': '/exercise-plates/hammer-curls.jpg', // <- Hammer Curls
  'preacher-curl-machine': '/exercise-plates/machine-preacher-curls.jpg', // <- Machine Preacher Curls
  'concentration-curl': '/exercise-plates/concentration-curls.jpg', // <- Concentration Curls
  'close-grip-bench-press': '/exercise-plates/close-grip-barbell-bench-press.jpg', // <- Close-Grip Barbell Bench Press
  'machine-overhead-tricep-extension': '/exercise-plates/machine-triceps-extension.jpg', // <- Machine Triceps Extension
  'front-squat': '/exercise-plates/front-barbell-squat.jpg', // <- Front Barbell Squat
  'leg-extension': '/exercise-plates/leg-extensions.jpg', // <- Leg Extensions
  'barbell-hip-thrust': '/exercise-plates/barbell-hip-thrust.jpg', // <- Barbell Hip Thrust
  'glute-bridge': '/exercise-plates/barbell-glute-bridge.jpg', // <- Barbell Glute Bridge
  'dumbbell-step-up': '/exercise-plates/step-up-with-knee-raise.jpg', // <- Step-up with Knee Raise
  'barbell-deadlift': '/exercise-plates/barbell-deadlift.jpg', // <- Barbell Deadlift
  'machine-back-extension': '/exercise-plates/hyperextensions-back-extensions.jpg', // <- Hyperextensions (Back Extensions)
  'hanging-knee-raise': '/exercise-plates/hanging-leg-raise.jpg', // <- Hanging Leg Raise
  'stairmaster': '/exercise-plates/stairmaster.jpg', // <- Stairmaster
};
