// shared/exercises/data.ts
// The exercise catalog — the SOLE display source for exercise metadata
// (muscles, equipment, instructions, default sets/reps for browse
// hints). The DB exercises table stores only coarse identity (name);
// this file owns everything shown about an exercise.
//
// 42 entries: 26 coarse identities placed on the AM/PM split (their
// slugs are the ExerciseKey union in splits.ts) + 16 browsable extras
// that get an exercises row on first log. Identity is by NAME — entries
// sharing a name are the same exercise row regardless of slug.
//
// Realization detail (grip, attachment, style) lives in the split's
// suggestedTags + the user's session tags — never in catalog entries.

import type { ExerciseType, DifficultyLevel } from '../types';
// ──────────────────────────────────────────────────────────────────────
// Muscle + equipment slugs (match seed SQL slugs)
// ──────────────────────────────────────────────────────────────────────

/**
 * Stable slugs for muscle reference rows. Mirrors the `slug` column added
 * catalog entries. Used to join exercises to muscles without
 * relying on UUID round-trips.
 */
export const MuscleSlug = {
  CHEST: 'chest',
  UPPER_CHEST: 'upper-chest',
  LOWER_CHEST: 'lower-chest',
  UPPER_BACK: 'upper-back',
  LATS: 'lats',
  LOWER_BACK: 'lower-back',
  TRAPS: 'traps',
  RHOMBOIDS: 'rhomboids',
  FRONT_DELTS: 'front-delts',
  SIDE_DELTS: 'side-delts',
  REAR_DELTS: 'rear-delts',
  BICEPS: 'biceps',
  TRICEPS: 'triceps',
  FOREARMS: 'forearms',
  ABS: 'abs',
  LOWER_ABS: 'lower-abs',
  OBLIQUES: 'obliques',
  QUADS: 'quads',
  HAMSTRINGS: 'hamstrings',
  GLUTES: 'glutes',
  CALVES: 'calves',
  TIBIALIS: 'tibialis',
} as const;

export type MuscleSlug = (typeof MuscleSlug)[keyof typeof MuscleSlug];

/** Stable slugs for equipment reference rows. */
export const EquipmentSlug = {
  BARBELL: 'barbell',
  DUMBBELL: 'dumbbell',
  KETTLEBELL: 'kettlebell',
  INCLINE_BENCH: 'incline-bench',
  FLAT_BENCH: 'flat-bench',
  DECLINE_BENCH: 'decline-bench',
  SQUAT_RACK: 'squat-rack',
  PULL_UP_BAR: 'pull-up-bar',
  CABLE_ROPE: 'cable-rope',
  CABLE_HANDLE: 'cable-handle',
  CABLE_STRAIGHT_BAR: 'cable-straight-bar',
  CABLE_V_BAR: 'cable-v-bar',
  CABLE_LAT_BAR: 'cable-lat-bar',
  LEG_PRESS_MACHINE: 'leg-press-machine',
  CHEST_FLY_MACHINE: 'chest-fly-machine',
  CHEST_PRESS_MACHINE: 'chest-press-machine',
  LAT_PULLDOWN_MACHINE: 'lat-pulldown-machine',
  SEATED_ROW_MACHINE: 'seated-row-machine',
  LEG_EXTENSION_MACHINE: 'leg-extension-machine',
  LEG_CURL_MACHINE: 'leg-curl-machine',
  HIP_ADDUCTION_MACHINE: 'hip-adduction-machine',
  CALF_RAISE_MACHINE: 'calf-raise-machine',
  TRICEP_EXTENSION_MACHINE: 'tricep-extension-machine',
  DIP_MACHINE: 'dip-machine',
  ABDOMINAL_MACHINE: 'abdominal-machine',
  BACK_EXTENSION_STATION: 'back-extension-station',
  CAPTAINS_CHAIR: 'captains-chair',
  RESISTANCE_BAND: 'resistance-band',
  TIBIA_RAISE_MACHINE: 'tibia-raise-machine',
  SHOULDER_PRESS_MACHINE: 'shoulder-press-machine',
  SHRUG_MACHINE: 'shrug-machine',
  HACK_SQUAT_MACHINE: 'hack-squat-machine',
  SEATED_CALF_RAISE_MACHINE: 'seated-calf-raise-machine',
  LYING_LEG_CURL_MACHINE: 'lying-leg-curl-machine',
  PEC_DECK_MACHINE: 'pec-deck-machine',
  FLOOR_SPACE: 'floor-space',
} as const;

export type EquipmentSlug = (typeof EquipmentSlug)[keyof typeof EquipmentSlug];

// ──────────────────────────────────────────────────────────────────────
// Display-name maps (slug → human string)
// ──────────────────────────────────────────────────────────────────────
// Local canonical display strings (historically mirrored the seed's
// display_name columns so attribute chips can render without a DB
// round-trip on the split-preview / active-session surfaces. If the two
// drift, the seed SQL is the source of truth — fix it here to match.

/** Modality slugs → words (the library list and detail header show these). */
export const EXERCISE_TYPE_DISPLAY: Record<ExerciseType, string> = {
  free_weight: 'Free weight',
  calisthenic: 'Bodyweight',
  machine: 'Machine',
  cable: 'Cable',
};

export const MUSCLE_DISPLAY_NAMES: Record<MuscleSlug, string> = {
  [MuscleSlug.CHEST]: 'Chest',
  [MuscleSlug.UPPER_CHEST]: 'Upper Chest',
  [MuscleSlug.LOWER_CHEST]: 'Lower Chest',
  [MuscleSlug.UPPER_BACK]: 'Upper Back',
  [MuscleSlug.LATS]: 'Lats',
  [MuscleSlug.LOWER_BACK]: 'Lower Back',
  [MuscleSlug.TRAPS]: 'Traps',
  [MuscleSlug.RHOMBOIDS]: 'Rhomboids',
  [MuscleSlug.FRONT_DELTS]: 'Front Delts',
  [MuscleSlug.SIDE_DELTS]: 'Side Delts',
  [MuscleSlug.REAR_DELTS]: 'Rear Delts',
  [MuscleSlug.BICEPS]: 'Biceps',
  [MuscleSlug.TRICEPS]: 'Triceps',
  [MuscleSlug.FOREARMS]: 'Forearms',
  [MuscleSlug.ABS]: 'Abs',
  [MuscleSlug.LOWER_ABS]: 'Lower Abs',
  [MuscleSlug.OBLIQUES]: 'Obliques',
  [MuscleSlug.QUADS]: 'Quads',
  [MuscleSlug.HAMSTRINGS]: 'Hamstrings',
  [MuscleSlug.GLUTES]: 'Glutes',
  [MuscleSlug.CALVES]: 'Calves',
  [MuscleSlug.TIBIALIS]: 'Tibialis',
};

export const EQUIPMENT_DISPLAY_NAMES: Record<EquipmentSlug, string> = {
  [EquipmentSlug.BARBELL]: 'Barbell',
  [EquipmentSlug.DUMBBELL]: 'Dumbbell',
  [EquipmentSlug.KETTLEBELL]: 'Kettlebell',
  [EquipmentSlug.INCLINE_BENCH]: 'Incline Bench',
  [EquipmentSlug.FLAT_BENCH]: 'Flat Bench',
  [EquipmentSlug.DECLINE_BENCH]: 'Decline Bench',
  [EquipmentSlug.SQUAT_RACK]: 'Squat Rack',
  [EquipmentSlug.PULL_UP_BAR]: 'Pull-up Bar',
  [EquipmentSlug.CABLE_ROPE]: 'Cable Rope',
  [EquipmentSlug.CABLE_HANDLE]: 'Cable Handle',
  [EquipmentSlug.CABLE_STRAIGHT_BAR]: 'Cable Straight Bar',
  [EquipmentSlug.CABLE_V_BAR]: 'Cable V-Bar',
  [EquipmentSlug.CABLE_LAT_BAR]: 'Cable Lat Bar',
  [EquipmentSlug.LEG_PRESS_MACHINE]: 'Leg Press Machine',
  [EquipmentSlug.CHEST_FLY_MACHINE]: 'Chest Fly Machine',
  [EquipmentSlug.CHEST_PRESS_MACHINE]: 'Chest Press Machine',
  [EquipmentSlug.LAT_PULLDOWN_MACHINE]: 'Lat Pulldown Machine',
  [EquipmentSlug.SEATED_ROW_MACHINE]: 'Seated Row Machine',
  [EquipmentSlug.LEG_EXTENSION_MACHINE]: 'Leg Extension Machine',
  [EquipmentSlug.LEG_CURL_MACHINE]: 'Leg Curl Machine',
  [EquipmentSlug.HIP_ADDUCTION_MACHINE]: 'Hip Adduction Machine',
  [EquipmentSlug.CALF_RAISE_MACHINE]: 'Calf Raise Machine',
  [EquipmentSlug.TRICEP_EXTENSION_MACHINE]: 'Tricep Extension Machine',
  [EquipmentSlug.DIP_MACHINE]: 'Dip Machine',
  [EquipmentSlug.ABDOMINAL_MACHINE]: 'Abdominal Machine',
  [EquipmentSlug.BACK_EXTENSION_STATION]: 'Back Extension Station',
  [EquipmentSlug.CAPTAINS_CHAIR]: "Captain's Chair",
  [EquipmentSlug.RESISTANCE_BAND]: 'Resistance Band',
  [EquipmentSlug.TIBIA_RAISE_MACHINE]: 'Tibia Raise Machine',
  [EquipmentSlug.SHOULDER_PRESS_MACHINE]: 'Shoulder Press Machine',
  [EquipmentSlug.SHRUG_MACHINE]: 'Shrug Machine',
  [EquipmentSlug.HACK_SQUAT_MACHINE]: 'Hack Squat Machine',
  [EquipmentSlug.SEATED_CALF_RAISE_MACHINE]: 'Seated Calf Raise Machine',
  [EquipmentSlug.LYING_LEG_CURL_MACHINE]: 'Lying Leg Curl Machine',
  [EquipmentSlug.PEC_DECK_MACHINE]: 'Pec Deck Machine',
  [EquipmentSlug.FLOOR_SPACE]: 'Floor Space',
};

// ──────────────────────────────────────────────────────────────────────
// Exercise data shape
// ──────────────────────────────────────────────────────────────────────

/**
 * Client-side exercise definition. Mirrors the exercises DB row plus its
 * junctions, keyed by slug (matches splits.ts ExerciseKey). The default
 * sets/reps are suggestions surfaced in the active-session UI when the
 * user adds the exercise to a draft.
 */
export interface SystemExerciseData {
  slug: string;
  name: string;
  /** Display category for the browse UI (Chest / Arms / etc.). */
  category: string;
  /**
   * Equipment modality — the substitution axis ('floor' = bodyweight).
   * DISPLAY-ONLY: groups the swap sheet's alternatives so movement
   * families offer floor / dumbbell / barbell / machine / cable options
   * where they genuinely exist.
   */
  modality?: 'floor' | 'dumbbell' | 'barbell' | 'machine' | 'cable';
  /**
   * Movement family — the substitution role ('chest-press',
   * 'vertical-pull', ...). DISPLAY-ONLY: families group the browse UI
   * and power the in-session swap sheet; they never affect identity,
   * history, or progression. Entries without a family simply offer no
   * same-family alternatives.
   */
  family?: string;
  /** Sub-label, e.g. 'Incline' or 'Cable'. */
  variation?: string;
  exerciseType: ExerciseType;
  difficultyLevel: DifficultyLevel;
  description: string;
  instructions: string;
  tips: string;
  /** Muscle slugs + primary/secondary flag. */
  primaryMuscles: MuscleSlug[];
  secondaryMuscles: MuscleSlug[];
  /** Equipment slugs + required/optional flag (default required). */
  equipment: Array<EquipmentSlug | { slug: EquipmentSlug; isRequired: boolean }>;
  /** Suggested sets (planning hint only). */
  defaultSets: number;
  /** Suggested rep range as [min, max]. */
  defaultReps: [number, number];
}

// ──────────────────────────────────────────────────────────────────────
// The 43 system exercises
// ──────────────────────────────────────────────────────────────────────


/**
 * The equipment union unwrapped — slugs only. The catalog admits both
 * bare slugs and `{slug, isRequired}` entries; consumers that just
 * need "what equipment" (display lines, zone ranking, swap reasons)
 * read this instead of re-deriving the unwrap at every call site.
 */
export function equipmentSlugs(
  exercise: Pick<SystemExerciseData, 'equipment'>,
): EquipmentSlug[] {
  return exercise.equipment.map((e) => (typeof e === 'string' ? e : e.slug));
}

/**
 * THE ZONES — the gym's geography, in walk order (free weights first,
 * the mats last). One home for the knowledge the library browses by
 * and the substitution ranking walks; the chips derive from it.
 */
export const ZONES: ReadonlyArray<{
  /** The catalog's equipment modality. */
  modality: NonNullable<SystemExerciseData['modality']>;
  /** The zone band's furniture-caps label. */
  zone: string;
  /** The filter chip's short mark. */
  chip: string;
}> = [
  { modality: 'barbell', zone: 'BARBELL', chip: 'BB' },
  { modality: 'dumbbell', zone: 'DUMBBELL', chip: 'DB' },
  { modality: 'cable', zone: 'CABLE COLUMN', chip: 'CB' },
  { modality: 'machine', zone: 'MACHINES', chip: 'M' },
  { modality: 'floor', zone: 'THE FLOOR', chip: 'BW' },
];

export const SYSTEM_EXERCISES: SystemExerciseData[] = [
  // ── Chest ──────────────────────────────────────────────────────────
  {
    slug: 'incline-barbell-press',
    modality: 'barbell',
    family: 'chest-press',
    name: 'Incline Barbell Press',
    category: 'Chest',
    exerciseType: 'free_weight',
    difficultyLevel: 'advanced',
    description:
      'Lie on an incline bench and press the barbell upward, focusing on upper chest activation.',
    instructions:
      'Set the incline to 30–45°. Grip slightly wider than shoulder-width. Lower the bar to the upper chest, then press up to full extension.',
    tips: 'Keep your lower back slightly arched; lower the bar to the upper part of your chest; ensure your elbows don\u2019t flare too much.',
    primaryMuscles: [MuscleSlug.UPPER_CHEST, MuscleSlug.FRONT_DELTS],
    secondaryMuscles: [MuscleSlug.TRICEPS, MuscleSlug.CHEST],
    equipment: [EquipmentSlug.BARBELL, EquipmentSlug.INCLINE_BENCH],
    defaultSets: 3,
    defaultReps: [6, 8],
  },
  {
    slug: 'incline-dumbbell-fly',
    modality: 'dumbbell',
    family: 'chest-fly',
    name: 'Incline Dumbbell Fly',
    category: 'Chest',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description:
      'Perform a fly movement with arms slightly bent while lying on an incline bench.',
    instructions:
      'With a slight elbow bend, lower the dumbbells in a wide arc until you feel a chest stretch, then squeeze back up.',
    tips: 'Keep a slight bend in your elbows throughout; focus on the stretch in your chest at the bottom; imagine you\u2019re hugging a barrel on the way up.',
    primaryMuscles: [MuscleSlug.UPPER_CHEST, MuscleSlug.CHEST],
    secondaryMuscles: [MuscleSlug.FRONT_DELTS],
    equipment: [EquipmentSlug.DUMBBELL, EquipmentSlug.INCLINE_BENCH],
    defaultSets: 2,
    defaultReps: [12, 15],
  },
  {
    slug: 'machine-chest-fly',
    modality: 'machine',
    family: 'chest-fly',
    name: 'Machine Chest Fly',
    category: 'Chest',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description:
      'Use the chest fly machine to perform a controlled fly movement that isolates the chest muscles.',
    instructions:
      'Adjust the seat so handles align with chest height. Bring the pads together in a wide arc and squeeze, then return under control.',
    tips: 'Adjust the seat height so handles align with chest; focus on squeezing your chest at the peak of contraction; control the eccentric (opening) phase.',
    primaryMuscles: [MuscleSlug.CHEST],
    secondaryMuscles: [MuscleSlug.FRONT_DELTS],
    equipment: [EquipmentSlug.CHEST_FLY_MACHINE],
    defaultSets: 2,
    defaultReps: [12, 15],
  },
  {
    slug: 'machine-incline-press',
    modality: 'machine',
    family: 'chest-press',
    name: 'Machine Incline Press',
    category: 'Chest',
    exerciseType: 'machine',
    difficultyLevel: 'intermediate',
    description:
      'Incline chest press machine targeting the upper chest with a controlled path.',
    instructions:
      'Set the seat to incline. Press the handles up to full extension, then lower under control.',
    tips: 'Keep the shoulder blades retracted; control the negative; full range of motion at the bottom.',
    primaryMuscles: [MuscleSlug.UPPER_CHEST, MuscleSlug.FRONT_DELTS],
    secondaryMuscles: [MuscleSlug.TRICEPS],
    equipment: [EquipmentSlug.CHEST_PRESS_MACHINE],
    defaultSets: 3,
    defaultReps: [8, 10],
  },

  // ── Arms ───────────────────────────────────────────────────────────
  {
    slug: 'cable-overhead-tricep-extension',
    modality: 'cable',
    family: 'elbow-extension-overhead',
    name: 'Cable Overhead Tricep Extension',
    category: 'Arms',
    exerciseType: 'cable',
    difficultyLevel: 'intermediate',
    description:
      'Using a rope attachment on a cable machine, extend your arms overhead to work the triceps.',
    instructions:
      'Attach a rope to a low pulley. Facing away, press the rope overhead to full tricep extension.',
    tips: 'Keep your upper arms stationary and close to your head; fully extend your elbows at the end of the movement; control the weight on the way back.',
    primaryMuscles: [MuscleSlug.TRICEPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.CABLE_ROPE],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'machine-dip',
    modality: 'machine',
    family: 'elbow-extension-press',
    name: 'Machine Dip',
    category: 'Arms',
    exerciseType: 'machine',
    difficultyLevel: 'intermediate',
    description:
      'Using a machine, perform dips to primarily target the triceps muscles.',
    instructions:
      'Sit upright on the assisted dip machine. Press the handles down to full arm extension.',
    tips: 'Keep your elbows tucked in to target triceps; control the descent without bouncing at the bottom; don\u2019t lock out the elbows at the top.',
    primaryMuscles: [MuscleSlug.TRICEPS],
    secondaryMuscles: [MuscleSlug.CHEST, MuscleSlug.FRONT_DELTS],
    equipment: [EquipmentSlug.TRICEP_EXTENSION_MACHINE],
    defaultSets: 2,
    defaultReps: [8, 10],
  },
  {
    slug: 'dumbbell-curl',
    modality: 'dumbbell',
    family: 'elbow-flexion',
    name: 'Dumbbell Curl',
    category: 'Arms',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description:
      'Seated incline dumbbell curl with arms hanging behind the torso for a deep bicep stretch.',
    instructions:
      'Set incline to 30–45°. With dumbbells at arm\u2019s length behind you, curl up without swinging.',
    tips: 'Let the arms hang fully at the bottom; squeeze at the top; avoid leaning forward to lift heavier.',
    primaryMuscles: [MuscleSlug.BICEPS],
    secondaryMuscles: [MuscleSlug.FOREARMS],
    equipment: [EquipmentSlug.DUMBBELL, EquipmentSlug.INCLINE_BENCH],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'cable-curl',
    modality: 'cable',
    family: 'elbow-flexion',
    name: 'Cable Curl',
    category: 'Arms',
    exerciseType: 'cable',
    difficultyLevel: 'beginner',
    description:
      'Cable curl with a rope attachment for continuous tension on the biceps.',
    instructions:
      'Attach a rope to a low pulley. Curl the rope toward your shoulders, squeezing at the top.',
    tips: 'Keep the elbows pinned to your sides; control the negative; avoid swinging.',
    primaryMuscles: [MuscleSlug.BICEPS],
    secondaryMuscles: [MuscleSlug.FOREARMS],
    equipment: [EquipmentSlug.CABLE_ROPE],
    defaultSets: 3,
    defaultReps: [10, 12],
  },

  // ── Shoulders ──────────────────────────────────────────────────────
  {
    slug: 'cable-lateral-raise',
    modality: 'cable',
    family: 'lateral-raise',
    name: 'Cable Lateral Raise',
    category: 'Shoulders',
    exerciseType: 'cable',
    difficultyLevel: 'intermediate',
    description:
      'Cable lateral raise leaning away from the stack (Egyptian style) for constant tension on the side delt.',
    instructions:
      'Set a low pulley. Stand side-on, lean away from the stack, and raise the handle out to shoulder height.',
    tips: 'Lead with the elbow; keep a slight bend; maintain the lean throughout for continuous tension.',
    primaryMuscles: [MuscleSlug.SIDE_DELTS],
    secondaryMuscles: [MuscleSlug.FRONT_DELTS, MuscleSlug.TRAPS],
    equipment: [EquipmentSlug.CABLE_HANDLE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'face-pull',
    modality: 'cable',
    family: 'face-pull',
    name: 'Face Pull',
    category: 'Shoulders',
    exerciseType: 'cable',
    difficultyLevel: 'intermediate',
    description:
      'Cable face pull with a rope attachment for rear delts and rotator cuff health.',
    instructions:
      'Set the pulley to face height. Pull the rope toward your face, splitting the ends outward.',
    tips: 'Keep the upper arms parallel to the floor; externally rotate at the top; use a moderate weight.',
    primaryMuscles: [MuscleSlug.REAR_DELTS],
    secondaryMuscles: [MuscleSlug.TRAPS, MuscleSlug.RHOMBOIDS],
    equipment: [EquipmentSlug.CABLE_ROPE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'shoulder-press',
    modality: 'machine',
    family: 'overhead-press',
    name: 'Shoulder Press',
    category: 'Shoulders',
    exerciseType: 'machine',
    difficultyLevel: 'intermediate',
    description:
      'Overhead shoulder press using either a machine or dumbbells, targeting the front and side delts.',
    instructions:
      'Sit upright (machine) or sit/stand with dumbbells at shoulder height. Press upward to full overhead extension, then lower under control.',
    tips: 'Don\u2019t lock out the elbows at the top; keep the core braced; avoid excessive lower-back arch.',
    primaryMuscles: [MuscleSlug.FRONT_DELTS, MuscleSlug.SIDE_DELTS],
    secondaryMuscles: [MuscleSlug.TRICEPS],
    equipment: [
      { slug: EquipmentSlug.SHOULDER_PRESS_MACHINE, isRequired: false },
      { slug: EquipmentSlug.DUMBBELL, isRequired: false },
    ],
    defaultSets: 2,
    defaultReps: [8, 10],
  },
  {
    slug: 'dumbbell-overhead-press',
    modality: 'dumbbell',
    family: 'overhead-press',
    name: 'Dumbbell Overhead Press',
    category: 'Shoulders',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description:
      'Standing or seated dumbbell overhead press for the front and side delts.',
    instructions:
      'Hold dumbbells at shoulder height. Press overhead to full extension, then lower under control.',
    tips: 'Brace the core; avoid excessive back arch; don\u2019t lock out the elbows at the top.',
    primaryMuscles: [MuscleSlug.FRONT_DELTS, MuscleSlug.SIDE_DELTS],
    secondaryMuscles: [MuscleSlug.TRICEPS],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 2,
    defaultReps: [8, 10],
  },

  // ── Back ───────────────────────────────────────────────────────────
  {
    slug: 'back-extension',
    modality: 'floor',
    family: 'hip-hinge-spinal-extension',
    name: 'Back Extension',
    category: 'Back',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description:
      'Bodyweight back extension on a Roman chair to target the lower back.',
    instructions:
      'Mount the back-extension station. Hinge at the hips, lower the torso, then raise back to neutral.',
    tips: 'Avoid hyperextension; move with control, not momentum; engage the glutes mildly at the top.',
    primaryMuscles: [MuscleSlug.LOWER_BACK],
    secondaryMuscles: [MuscleSlug.GLUTES, MuscleSlug.HAMSTRINGS],
    equipment: [EquipmentSlug.BACK_EXTENSION_STATION],
    defaultSets: 2,
    defaultReps: [10, 12],
  },
  {
    slug: 'cable-row',
    modality: 'cable',
    family: 'horizontal-pull',
    name: 'Cable Row',
    category: 'Back',
    exerciseType: 'cable',
    difficultyLevel: 'intermediate',
    description:
      'Seated cable row with a V-grip attachment targeting the lats and upper back.',
    instructions:
      'Sit upright at the cable row station. Pull the V-grip to your lower chest, squeezing the shoulder blades.',
    tips: 'Keep the torso upright; lead with the elbows; full stretch at the bottom without rounding the spine.',
    primaryMuscles: [MuscleSlug.LATS, MuscleSlug.UPPER_BACK],
    secondaryMuscles: [MuscleSlug.BICEPS, MuscleSlug.RHOMBOIDS],
    equipment: [EquipmentSlug.CABLE_V_BAR],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'lat-pulldown',
    modality: 'machine',
    family: 'vertical-pull',
    name: 'Lat Pulldown',
    category: 'Back',
    exerciseType: 'cable',
    difficultyLevel: 'intermediate',
    description:
      'Lat pulldown with a shoulder-width reverse (underhand) grip to bias the lats and biceps.',
    instructions:
      'Grip the bar shoulder-width with palms facing you. Pull to the upper chest, then control back up.',
    tips: 'Lead with the elbows; avoid leaning back excessively; full overhead stretch at the top.',
    primaryMuscles: [MuscleSlug.LATS],
    secondaryMuscles: [MuscleSlug.BICEPS, MuscleSlug.UPPER_BACK],
    equipment: [EquipmentSlug.CABLE_LAT_BAR],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'straight-arm-pulldown',
    modality: 'cable',
    family: 'vertical-pull-straight-arm',
    name: 'Straight-Arm Pulldown',
    category: 'Back',
    exerciseType: 'cable',
    difficultyLevel: 'intermediate',
    description:
      'Cable pulldown with straight arms to isolate the lats without biceps involvement.',
    instructions:
      'Attach a rope to a high pulley. With arms straight, press the rope down toward your thighs.',
    tips: 'Keep arms straight throughout; lead with the lats, not the triceps; avoid leaning forward.',
    primaryMuscles: [MuscleSlug.LATS],
    secondaryMuscles: [MuscleSlug.CHEST],
    equipment: [EquipmentSlug.CABLE_ROPE],
    defaultSets: 3,
    defaultReps: [12, 15],
  },
  {
    slug: 'machine-shrug',
    modality: 'machine',
    family: 'scapular-elevation',
    name: 'Machine Shrug',
    category: 'Back',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description:
      'Plate-loaded shrug machine for targeted trap development with minimal lower-back involvement.',
    instructions:
      'Sit or stand in the shrug machine. Shrug the shoulders straight up toward the ears, then lower under control.',
    tips: 'Don\u2019t roll the shoulders; pause at peak contraction; avoid jerking the weight up.',
    primaryMuscles: [MuscleSlug.TRAPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.SHRUG_MACHINE],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'dumbbell-shrug',
    modality: 'dumbbell',
    family: 'scapular-elevation',
    name: 'Dumbbell Shrug',
    category: 'Back',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'Standing dumbbell shrug for targeted trap development.',
    instructions:
      'Hold dumbbells at your sides. Shrug the shoulders straight up toward the ears, then lower under control.',
    tips: 'Don\u2019t roll the shoulders; pause at peak contraction; avoid jerking the weight up.',
    primaryMuscles: [MuscleSlug.TRAPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [8, 10],
  },

  // ── Upper leg ──────────────────────────────────────────────────────
  {
    slug: 'leg-press',
    modality: 'machine',
    family: 'knee-dominant-bilateral',
    name: 'Leg Press',
    category: 'Upper Leg',
    exerciseType: 'machine',
    difficultyLevel: 'advanced',
    description: 'Push weight away from your body using your legs on a leg press machine.',
    instructions:
      'Sit in the leg press with feet shoulder-width on the platform. Lower to ~90°, then press back up.',
    tips: 'Don\u2019t lock out your knees at the top; place feet shoulder-width apart for balanced development; lower until your knees reach about 90 degrees.',
    primaryMuscles: [MuscleSlug.QUADS, MuscleSlug.GLUTES],
    secondaryMuscles: [MuscleSlug.HAMSTRINGS, MuscleSlug.CALVES],
    equipment: [EquipmentSlug.LEG_PRESS_MACHINE],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'bulgarian-split-squat',
    modality: 'dumbbell',
    family: 'knee-dominant-unilateral',
    name: 'Bulgarian Split Squat',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'advanced',
    description:
      'Dumbbell split squat with the rear foot elevated on a bench, targeting the quads and glutes.',
    instructions:
      'Hold dumbbells. Place rear foot on a bench behind you. Lower the front thigh to parallel, then drive up.',
    tips: 'Track the front knee over the toe; keep the torso upright; control the descent.',
    primaryMuscles: [MuscleSlug.QUADS, MuscleSlug.GLUTES],
    secondaryMuscles: [MuscleSlug.HAMSTRINGS],
    equipment: [EquipmentSlug.DUMBBELL, EquipmentSlug.FLAT_BENCH],
    defaultSets: 2,
    defaultReps: [8, 10],
  },
  {
    slug: 'machine-leg-curl',
    modality: 'machine',
    family: 'knee-flexion',
    name: 'Machine Leg Curl',
    category: 'Upper Leg',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description: 'Seated leg curl machine targeting the hamstrings.',
    instructions:
      'Sit on the leg curl. Hook the lower pad above the heels. Curl backward by bending the knees.',
    tips: 'Squeeze the hamstrings at peak contraction; avoid jerking; control the negative.',
    primaryMuscles: [MuscleSlug.HAMSTRINGS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.LEG_CURL_MACHINE],
    defaultSets: 3,
    defaultReps: [8, 10],
  },

  // ── Lower leg ──────────────────────────────────────────────────────
  {
    slug: 'tibia-raise',
    modality: 'machine',
    family: 'dorsi-flexion',
    name: 'Tibia Raise',
    category: 'Lower Leg',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description: 'Raise your foot upward against resistance to target the tibialis anterior.',
    instructions:
      'Anchor a band or use a tib-raise machine. Dorsiflex the foot against resistance.',
    tips: 'Focus on the pulling motion from your foot, not your leg; control both phases; can be performed seated or standing.',
    primaryMuscles: [MuscleSlug.TIBIALIS],
    secondaryMuscles: [],
    equipment: [
      { slug: EquipmentSlug.TIBIA_RAISE_MACHINE, isRequired: false },
      { slug: EquipmentSlug.RESISTANCE_BAND, isRequired: false },
    ],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'leg-press-calf-raise',
    modality: 'machine',
    family: 'plantar-flexion',
    name: 'Leg Press Calf Raise',
    category: 'Lower Leg',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description: 'Calf raise performed on the leg press platform.',
    instructions:
      'Sit in the leg press. Place the balls of the feet on the lower edge of the platform. Press away via ankle plantarflexion.',
    tips: 'Full range of motion at the ankle; pause at peak contraction; avoid bouncing.',
    primaryMuscles: [MuscleSlug.CALVES],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.LEG_PRESS_MACHINE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'standing-machine-calf-raise',
    modality: 'machine',
    family: 'plantar-flexion',
    name: 'Standing Machine Calf Raise',
    category: 'Lower Leg',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description: 'Standing calf raise machine targeting the gastrocnemius.',
    instructions:
      'Stand in the calf raise machine. Lower the heels fully, then press up to the toes.',
    tips: 'Full stretch at the bottom; pause at peak; avoid bouncing.',
    primaryMuscles: [MuscleSlug.CALVES],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.CALF_RAISE_MACHINE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },

  // ── Abs ────────────────────────────────────────────────────────────
  {
    slug: 'leg-raise',
    modality: 'machine',
    family: 'vertical-leg-raise',
    name: 'Leg Raise',
    category: 'Abs',
    exerciseType: 'calisthenic',
    difficultyLevel: 'advanced',
    description: "Support yourself on a captain's chair and raise your legs upward to target the lower abdominals.",
    instructions:
      'Support the forearms on the captain\u2019s chair pads. Raise the legs to hip height, then lower under control.',
    tips: 'Avoid swinging or using momentum; try to curl your pelvis upward at the top; control the descent rather than dropping your legs.',
    primaryMuscles: [MuscleSlug.LOWER_ABS, MuscleSlug.ABS],
    secondaryMuscles: [MuscleSlug.OBLIQUES, MuscleSlug.QUADS],
    equipment: [EquipmentSlug.CAPTAINS_CHAIR],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'machine-ab-crunch',
    modality: 'machine',
    family: 'trunk-flexion',
    name: 'Machine Ab Crunch',
    category: 'Abs',
    exerciseType: 'machine',
    difficultyLevel: 'intermediate',
    description: 'Ab crunch machine with a slow eccentric phase to bias the rectus abdominis.',
    instructions:
      'Sit in the ab crunch machine. Crunch forward with a 3-second negative.',
    tips: 'Squeeze at peak contraction; control the negative for 3 seconds; avoid using the hip flexors.',
    primaryMuscles: [MuscleSlug.ABS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.ABDOMINAL_MACHINE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },

  // ── Substitution pool ──────────────────────────────────────────────
  // Browsable extras — NOT placed on a oneADay/twoADay split day. They
  // get an exercises row on first log. The defaultSets/defaultReps are
  // display hints mirrored from the historical template prescriptions in
  // 20260721000002 Step 14 where the exercise appears in the
  // two-a-day template, and fall back to conventional defaults elsewhere.
  {
    slug: 'hack-squat-machine',
    modality: 'machine',
    family: 'knee-dominant-bilateral',
    name: 'Hack Squat',
    variation: 'Machine',
    category: 'Upper Leg',
    exerciseType: 'machine',
    difficultyLevel: 'intermediate',
    description:
      'Machine hack squat targeting the quads through a controlled vertical-path squat with the shoulders stabilized.',
    instructions:
      'Place shoulders under the pads, feet shoulder-width on the platform. Lower until thighs reach ~90°, then press through the heels.',
    tips: 'Keep the lower back flat against the pad; don\u2019t lock the knees at the top; control the negative.',
    primaryMuscles: [MuscleSlug.QUADS, MuscleSlug.GLUTES],
    secondaryMuscles: [MuscleSlug.HAMSTRINGS, MuscleSlug.CALVES],
    equipment: [EquipmentSlug.HACK_SQUAT_MACHINE],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'seated-calf-raise-machine',
    modality: 'machine',
    family: 'plantar-flexion',
    name: 'Seated Calf Raise',
    variation: 'Machine',
    category: 'Lower Leg',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description:
      'Seated calf raise machine biases the soleus and biases gastrocnemius less than the standing variant due to the bent-knee position.',
    instructions:
      'Sit with the balls of the feet on the platform and the pad across the thighs. Lower the heels, then press up to full plantar-flexion.',
    tips: 'Pause at the top; control the negative; full range of motion at the bottom.',
    primaryMuscles: [MuscleSlug.CALVES],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.SEATED_CALF_RAISE_MACHINE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'romanian-deadlift-barbell',
    modality: 'barbell',
    family: 'hip-hinge-spinal-extension',
    name: 'Romanian Deadlift',
    variation: 'Barbell',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'advanced',
    description:
      'Barbell Romanian deadlift — a hip-hinge with mostly-straight knees targeting the hamstrings and lower back.',
    instructions:
      'Grip the bar shoulder-width. Hinge at the hips with soft knees, lowering the bar along the thighs until you feel a hamstring stretch.',
    tips: 'Keep the bar close to the legs; maintain a neutral spine; don\u2019t turn it into a squat by bending the knees too much.',
    primaryMuscles: [MuscleSlug.HAMSTRINGS, MuscleSlug.LOWER_BACK],
    secondaryMuscles: [MuscleSlug.GLUTES, MuscleSlug.TRAPS],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'floor-leg-raise',
    modality: 'floor',
    family: 'vertical-leg-raise',
    name: 'Floor Leg Raise',
    variation: 'Lying',
    category: 'Abs',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description:
      'Bodyweight leg raise performed lying on the floor, targeting the lower abs through hip flexion.',
    instructions:
      'Lie flat on the floor, legs straight. Raise both legs to vertical, then lower under control without touching the floor.',
    tips: 'Keep the lower back pressed to the floor; avoid swinging; bend the knees to reduce difficulty.',
    primaryMuscles: [MuscleSlug.LOWER_ABS, MuscleSlug.ABS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.FLOOR_SPACE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'incline-dumbbell-press',
    modality: 'dumbbell',
    family: 'chest-press',
    name: 'Incline Dumbbell Press',
    variation: 'Incline',
    category: 'Chest',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description:
      'Incline dumbbell press for the upper chest, allowing a deeper stretch and independent arm path than the barbell variant.',
    instructions:
      'Set the incline to 30–45°. Press the dumbbells from shoulder-level overhead in a controlled arc.',
    tips: 'Keep a 45° elbow angle from the torso; control the negative; full range of motion at the bottom.',
    primaryMuscles: [MuscleSlug.UPPER_CHEST, MuscleSlug.FRONT_DELTS],
    secondaryMuscles: [MuscleSlug.TRICEPS, MuscleSlug.CHEST],
    equipment: [EquipmentSlug.DUMBBELL, EquipmentSlug.INCLINE_BENCH],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'overhead-dumbbell-tricep-extension',
    modality: 'dumbbell',
    family: 'elbow-extension-overhead',
    name: 'Overhead Tricep Extension',
    variation: 'Dumbbell',
    category: 'Arms',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description:
      'Overhead dumbbell triceps extension, typically performed one arm at a time with a single dumbbell.',
    instructions:
      'Hold a single dumbbell overhead with both hands (or one). Lower behind the head, then press back to full extension.',
    tips: 'Keep the upper arms stationary; don\u2019t flare the elbows; control the negative.',
    primaryMuscles: [MuscleSlug.TRICEPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'barbell-overhead-press',
    modality: 'barbell',
    family: 'overhead-press',
    name: 'Overhead Press',
    variation: 'Barbell',
    category: 'Shoulders',
    exerciseType: 'free_weight',
    difficultyLevel: 'advanced',
    description:
      'Standing barbell overhead press for the front and side delts, with substantial core and upper-back stability demand.',
    instructions:
      'Grip the bar shoulder-width. Press from the front-rack position overhead to full extension, then lower under control.',
    tips: 'Brace the core; avoid excessive lower-back arch; don\u2019t bounce at the bottom.',
    primaryMuscles: [MuscleSlug.FRONT_DELTS, MuscleSlug.SIDE_DELTS],
    secondaryMuscles: [MuscleSlug.TRICEPS],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 3,
    defaultReps: [6, 8],
  },
  {
    slug: 'dumbbell-lateral-raise',
    modality: 'dumbbell',
    family: 'lateral-raise',
    name: 'Lateral Raise',
    variation: 'Dumbbell',
    category: 'Shoulders',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description:
      'Standing dumbbell lateral raise to target the side deltoids through shoulder abduction.',
    instructions:
      'Hold dumbbells at your sides. Raise out to shoulder height with a slight elbow bend, then lower under control.',
    tips: 'Lead with the elbows; avoid shrugging; don\u2019t swing.',
    primaryMuscles: [MuscleSlug.SIDE_DELTS],
    secondaryMuscles: [MuscleSlug.FRONT_DELTS],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'lying-leg-curl-machine',
    modality: 'machine',
    family: 'knee-flexion',
    name: 'Lying Leg Curl',
    variation: 'Machine',
    category: 'Upper Leg',
    exerciseType: 'machine',
    difficultyLevel: 'intermediate',
    description:
      'Lying leg curl machine targeting the hamstrings through knee flexion, performed prone.',
    instructions:
      'Lie prone on the machine with the pad against the lower calves. Curl the pad toward the hips, then lower under control.',
    tips: 'Keep the hips pressed to the pad; don\u2019t hyperextend the lower back; pause at peak contraction.',
    primaryMuscles: [MuscleSlug.HAMSTRINGS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.LYING_LEG_CURL_MACHINE],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'pull-up-bar',
    modality: 'machine',
    family: 'vertical-pull',
    name: 'Pull-up',
    variation: 'Bar',
    category: 'Back',
    exerciseType: 'calisthenic',
    difficultyLevel: 'advanced',
    description:
      'Bodyweight pull-up on a bar for vertical-pull strength, primarily targeting the lats and biceps.',
    instructions:
      'Hang from the bar with overhand grip. Pull until the chin clears the bar, then lower under control.',
    tips: 'Lead with the chest; full hang at the bottom; avoid kipping.',
    primaryMuscles: [MuscleSlug.LATS, MuscleSlug.BICEPS],
    secondaryMuscles: [MuscleSlug.UPPER_BACK],
    equipment: [EquipmentSlug.PULL_UP_BAR],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'cable-rope-crunch',
    modality: 'cable',
    family: 'trunk-flexion',
    name: 'Cable Crunch',
    variation: 'Rope',
    category: 'Abs',
    exerciseType: 'cable',
    difficultyLevel: 'intermediate',
    description:
      'Cable crunch with a rope attachment on a high pulley, loading spinal flexion for the abs.',
    instructions:
      'Kneel below a high pulley with the rope behind the head. Crunch down by flexing the spine, then return under control.',
    tips: 'Curl the spine; don\u2019t hinge at the hips; pause at peak contraction.',
    primaryMuscles: [MuscleSlug.ABS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.CABLE_ROPE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'cable-wood-chop',
    modality: 'cable',
    family: 'trunk-rotation',
    name: 'Cable Wood Chop',
    category: 'Abs',
    exerciseType: 'cable',
    difficultyLevel: 'intermediate',
    description:
      'High-to-low cable wood chop — loaded trunk rotation carrying the handle diagonally across the body, the obliques\u2019 signature lift.',
    instructions:
      'Stand side-on to a high pulley with a rope or handle in both hands. Pull down and across to the far hip, rotating through the ribs, then return under control.',
    tips: 'Rotate from the ribs, not the arms; keep the hips quiet; the controlled return is half the work.',
    primaryMuscles: [MuscleSlug.OBLIQUES],
    secondaryMuscles: [MuscleSlug.ABS],
    equipment: [EquipmentSlug.CABLE_ROPE],
    defaultSets: 3,
    defaultReps: [12, 15],
  },
  {
    slug: 'walking-lunge-dumbbell',
    modality: 'dumbbell',
    family: 'knee-dominant-unilateral',
    name: 'Walking Lunge',
    variation: 'Dumbbell',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description:
      'Dumbbell walking lunge for unilateral quad and glute development with dynamic balance demand.',
    instructions:
      'Hold dumbbells at your sides. Step forward, lower until the back knee nearly touches the floor, then push through to step into the next rep.',
    tips: 'Keep the torso upright; don\u2019t let the front knee cave inward; full hip extension between steps.',
    primaryMuscles: [MuscleSlug.QUADS, MuscleSlug.GLUTES],
    secondaryMuscles: [MuscleSlug.HAMSTRINGS, MuscleSlug.CALVES],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 2,
    defaultReps: [8, 10],
  },
  {
    slug: 'dumbbell-pullover',
    modality: 'dumbbell',
    family: 'vertical-pull-straight-arm',
    name: 'Dumbbell Pullover',
    variation: 'Flat Bench',
    category: 'Back',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description:
      'Dumbbell pullover across a flat bench, targeting the lats through shoulder extension with some chest involvement.',
    instructions:
      'Lie upper-back across a flat bench. Lower a single dumbbell overhead behind you, then pull back over the chest.',
    tips: 'Keep a slight elbow bend; focus on the lat stretch; avoid letting the hips sag.',
    primaryMuscles: [MuscleSlug.LATS, MuscleSlug.UPPER_CHEST],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.DUMBBELL, EquipmentSlug.FLAT_BENCH],
    defaultSets: 3,
    defaultReps: [12, 15],
  },
  {
    slug: 'bench-dip',
    modality: 'floor',
    family: 'elbow-extension-press',
    name: 'Bench Dip',
    variation: 'Bodyweight',
    category: 'Arms',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description:
      'Bodyweight triceps dip off a flat bench, with the feet on the floor or elevated.',
    instructions:
      'Sit on the edge of a bench, hands beside the hips. Slide off and lower by bending the elbows, then press back up.',
    tips: 'Keep the elbows pointing back, not out; control the descent; don\u2019t shrug the shoulders.',
    primaryMuscles: [MuscleSlug.TRICEPS],
    secondaryMuscles: [MuscleSlug.FRONT_DELTS],
    equipment: [EquipmentSlug.FLAT_BENCH],
    defaultSets: 3,
    defaultReps: [12, 15],
  },
  {
    slug: 'barbell-row',
    modality: 'barbell',
    family: 'horizontal-pull',
    name: 'Barbell Row',
    variation: 'Bent-Over',
    category: 'Back',
    exerciseType: 'free_weight',
    difficultyLevel: 'advanced',
    description:
      'Hinge-supported barbell row for the lats and upper back, loaded through the posterior chain.',
    instructions:
      'Hinge at the hips with a flat back. Pull the bar to the lower chest, squeezing the shoulder blades, then lower under control.',
    tips: 'Keep the back flat; lead with the elbows; avoid using the lower back to row the weight.',
    primaryMuscles: [MuscleSlug.LATS, MuscleSlug.UPPER_BACK],
    secondaryMuscles: [MuscleSlug.BICEPS, MuscleSlug.REAR_DELTS],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'push-up',
    modality: 'floor',
    family: 'chest-press',
    name: 'Push-Up',
    category: 'Chest',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description: 'The floor pressing standard — chest, front delts, and triceps with no equipment.',
    instructions: 'Hands under the shoulders, body straight. Lower the chest to the floor and press back up.',
    tips: 'Squeeze the glutes to lock the line; elbows ~45° from the torso; full lockout each rep.',
    primaryMuscles: [MuscleSlug.CHEST],
    secondaryMuscles: [MuscleSlug.TRICEPS, MuscleSlug.FRONT_DELTS],
    equipment: [EquipmentSlug.FLOOR_SPACE],
    defaultSets: 3,
    defaultReps: [10, 15],
  },
  {
    slug: 'barbell-back-squat',
    modality: 'barbell',
    family: 'knee-dominant-bilateral',
    name: 'Barbell Back Squat',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'The barbell squat — the bilateral knee-dominant fundamental.',
    instructions: 'Bar on the traps, feet shoulder-width. Sit down between the hips to depth, drive up through the mid-foot.',
    tips: 'Brace before every rep; knees track over the toes; hit at least parallel.',
    primaryMuscles: [MuscleSlug.QUADS],
    secondaryMuscles: [MuscleSlug.GLUTES, MuscleSlug.HAMSTRINGS],
    equipment: [EquipmentSlug.BARBELL, EquipmentSlug.SQUAT_RACK],
    defaultSets: 3,
    defaultReps: [6, 10],
  },
  {
    slug: 'dumbbell-goblet-squat',
    modality: 'dumbbell',
    family: 'knee-dominant-bilateral',
    name: 'Dumbbell Goblet Squat',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'A dumbbell held at the chest — the friendliest loaded bilateral squat.',
    instructions: 'Hold one dumbbell at the chest. Squat down between the heels, keep the chest tall, drive up.',
    tips: 'Elbows inside the knees at the bottom; the weight counterbalances you upright.',
    primaryMuscles: [MuscleSlug.QUADS],
    secondaryMuscles: [MuscleSlug.GLUTES],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'bodyweight-squat',
    modality: 'floor',
    family: 'knee-dominant-bilateral',
    name: 'Bodyweight Squat',
    category: 'Upper Leg',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description: 'The unloaded squat — the floor option for bilateral knee-dominant work.',
    instructions: 'Feet shoulder-width, squat to depth, stand tall. Controlled tempo both ways.',
    tips: 'Slow eccentrics make these earn their place; pause at the bottom for more.',
    primaryMuscles: [MuscleSlug.QUADS],
    secondaryMuscles: [MuscleSlug.GLUTES],
    equipment: [EquipmentSlug.FLOOR_SPACE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'barbell-standing-calf-raise',
    modality: 'barbell',
    family: 'plantar-flexion',
    name: 'Barbell Standing Calf Raise',
    category: 'Lower Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Bar on the traps, calves do the work — the free-weight standing calf raise.',
    instructions: 'Bar as for a squat, balls of the feet on a plate or block. Rise to the top of the toes, lower to a stretch.',
    tips: 'Full stretch at the bottom, hard squeeze at the top; no bouncing.',
    primaryMuscles: [MuscleSlug.CALVES],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 3,
    defaultReps: [10, 15],
  },
  {
    slug: 'dumbbell-standing-calf-raise',
    modality: 'dumbbell',
    family: 'plantar-flexion',
    name: 'Dumbbell Standing Calf Raise',
    category: 'Lower Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'Dumbbells at the sides — the dumbbell standing calf raise.',
    instructions: 'Hold dumbbells, balls of the feet on a block. Rise to the toes, lower under control.',
    tips: 'Keep the knees nearly locked; the range lives in the ankle.',
    primaryMuscles: [MuscleSlug.CALVES],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [12, 15],
  },
  {
    slug: 'single-leg-calf-raise',
    modality: 'floor',
    family: 'plantar-flexion',
    name: 'Single-Leg Calf Raise',
    category: 'Lower Leg',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description: 'One leg, bodyweight, full range — the anywhere calf raise.',
    instructions: 'Stand on one foot on a step edge. Rise to the toes, lower to a deep stretch.',
    tips: 'Hold a wall for balance only; per-leg — match reps both sides.',
    primaryMuscles: [MuscleSlug.CALVES],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.FLOOR_SPACE],
    defaultSets: 3,
    defaultReps: [12, 15],
  },
  {
    slug: 'dumbbell-romanian-deadlift',
    modality: 'dumbbell',
    family: 'hip-hinge-spinal-extension',
    name: 'Dumbbell Romanian Deadlift',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Dumbbells, hip hinge, hamstring stretch — the RDL with free weights.',
    instructions: 'Dumbbells at the thighs, soft knees. Push the hips back until the hamstrings load, stand tall.',
    tips: 'The hips travel back, not down; the back stays flat; feel the stretch not the floor.',
    primaryMuscles: [MuscleSlug.HAMSTRINGS],
    secondaryMuscles: [MuscleSlug.GLUTES],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'barbell-overhead-tricep-extension',
    modality: 'barbell',
    family: 'elbow-extension-overhead',
    name: 'Barbell Overhead Tricep Extension',
    category: 'Arms',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Bar (or EZ bar) overhead — the barbell long-head tricep builder.',
    instructions: 'Press the bar overhead, lower behind the head by bending the elbows, extend back up.',
    tips: 'Elbows point up and stay narrow; lower deep for the long-head stretch.',
    primaryMuscles: [MuscleSlug.TRICEPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'pike-push-up',
    modality: 'floor',
    family: 'overhead-press',
    name: 'Pike Push-Up',
    category: 'Shoulders',
    exerciseType: 'calisthenic',
    difficultyLevel: 'intermediate',
    description: 'Hips high, head to the floor — the bodyweight overhead press.',
    instructions: 'From a pike (hips stacked over the shoulders), lower the crown of the head toward the floor and press back up.',
    tips: 'The tighter the pike the more shoulder; elevate the feet to load it further.',
    primaryMuscles: [MuscleSlug.FRONT_DELTS],
    secondaryMuscles: [MuscleSlug.TRICEPS],
    equipment: [EquipmentSlug.FLOOR_SPACE],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'dumbbell-rear-delt-fly',
    modality: 'dumbbell',
    family: 'face-pull',
    name: 'Dumbbell Rear Delt Fly',
    category: 'Shoulders',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'Bent over, fly rearward — the dumbbell rear-delt option.',
    instructions: 'Hinge to near-parallel, dumbbells hanging. Fly out to the sides with a flat back, lower slowly.',
    tips: 'Lead with the pinkies; think shoulder-blade width, not squeeze.',
    primaryMuscles: [MuscleSlug.REAR_DELTS],
    secondaryMuscles: [MuscleSlug.UPPER_BACK],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [12, 15],
  },
  {
    slug: 'barbell-shrug',
    modality: 'barbell',
    family: 'scapular-elevation',
    name: 'Barbell Shrug',
    category: 'Back',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'Bar in the hands, shrug to the ears — the classic barbell trap builder.',
    instructions: 'Stand tall with the bar at arms\' length. Shrug straight up, pause, lower fully.',
    tips: 'No rolling; full stretch at the bottom loads the traps through range.',
    primaryMuscles: [MuscleSlug.TRAPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'cable-chest-fly',
    modality: 'cable',
    family: 'chest-fly',
    name: 'Cable Chest Fly',
    category: 'Chest',
    exerciseType: 'cable',
    difficultyLevel: 'beginner',
    description: 'Cable columns, constant tension — the cable fly.',
    instructions: 'Set pulleys high, step forward, sweep the handles together in a hugging arc.',
    tips: 'Slight elbow bend held fixed; resist on the way open — that half is the exercise.',
    primaryMuscles: [MuscleSlug.CHEST],
    secondaryMuscles: [MuscleSlug.FRONT_DELTS],
    equipment: [EquipmentSlug.CABLE_HANDLE],
    defaultSets: 3,
    defaultReps: [12, 15],
  },
  {
    slug: 'nordic-hamstring-curl',
    modality: 'floor',
    family: 'knee-flexion',
    name: 'Nordic Hamstring Curl',
    category: 'Upper Leg',
    exerciseType: 'calisthenic',
    difficultyLevel: 'advanced',
    description: 'Anchored ankles, lower forward — the brutal floor hamstring curl.',
    instructions: 'Kneel with ankles anchored. Lower the torso forward as slowly as the hamstrings allow, catch with the hands, pull back up.',
    tips: 'Fight the eccentric for seconds per rep; a band assists between floor and machine.',
    primaryMuscles: [MuscleSlug.HAMSTRINGS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.FLOOR_SPACE],
    defaultSets: 3,
    defaultReps: [6, 10],
  },
  {
    slug: 'dumbbell-leg-curl',
    modality: 'dumbbell',
    family: 'knee-flexion',
    name: 'Dumbbell Leg Curl',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Dumbbell between the feet — the free-weight leg curl.',
    instructions: 'Lie prone on a bench, dumbbell between the feet. Curl the heels to the hips, lower slowly.',
    tips: 'Squeeze the dumbbell hard so it stays put; control beats load here.',
    primaryMuscles: [MuscleSlug.HAMSTRINGS],
    secondaryMuscles: [MuscleSlug.CALVES],
    equipment: [EquipmentSlug.DUMBBELL, EquipmentSlug.FLAT_BENCH],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'floor-crunch',
    modality: 'floor',
    family: 'trunk-flexion',
    name: 'Floor Crunch',
    category: 'Abs',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description: 'The floor trunk-flexion standard — no equipment, honest reps.',
    instructions: 'Lie back, knees bent. Curl the ribs toward the hips, lower with control.',
    tips: 'Slow exhale at the top; the range is short — make the squeeze the rep.',
    primaryMuscles: [MuscleSlug.ABS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.FLOOR_SPACE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'barbell-curl',
    modality: 'barbell',
    family: 'elbow-flexion',
    name: 'Barbell Curl',
    category: 'Arms',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'Straight bar, both arms — the barbell biceps standard.',
    instructions: 'Bar at arms\' length, elbows pinned. Curl to the shoulders, lower fully.',
    tips: 'No hip swing; the elbows stay at your sides from first rep to last.',
    primaryMuscles: [MuscleSlug.BICEPS],
    secondaryMuscles: [MuscleSlug.FOREARMS],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'barbell-split-squat',
    modality: 'barbell',
    family: 'knee-dominant-unilateral',
    name: 'Barbell Split Squat',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Bar on the back, rear-foot split squat — the heavily loaded unilateral squat.',
    instructions: 'Bar on the traps, one foot far forward. Drop the back knee toward the floor, drive up through the front leg.',
    tips: 'Front shin stays near-vertical; torso tall; per-leg — match reps both sides.',
    primaryMuscles: [MuscleSlug.QUADS],
    secondaryMuscles: [MuscleSlug.GLUTES],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 2,
    defaultReps: [8, 10],
  },
  {
    slug: 'pistol-squat',
    modality: 'floor',
    family: 'knee-dominant-unilateral',
    name: 'Pistol Squat',
    category: 'Upper Leg',
    exerciseType: 'calisthenic',
    difficultyLevel: 'advanced',
    description: 'One leg, full depth, other leg extended — the bodyweight unilateral king.',
    instructions: 'Stand on one leg, extend the other forward. Sit to full depth on the standing leg and stand back up.',
    tips: 'Hold a counterweight to make these easier; ankle mobility is the gate.',
    primaryMuscles: [MuscleSlug.QUADS],
    secondaryMuscles: [MuscleSlug.GLUTES],
    equipment: [EquipmentSlug.FLOOR_SPACE],
    defaultSets: 3,
    defaultReps: [6, 8],
  },
  {
    slug: 'barbell-pullover',
    modality: 'barbell',
    family: 'vertical-pull-straight-arm',
    name: 'Barbell Pullover',
    category: 'Back',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Bar from overhead to chest — the old-school straight-arm lat builder.',
    instructions: 'Lie on a bench, bar extended above the chest. Lower overhead in an arc, pull back to above the chest.',
    tips: 'Elbows nearly fixed — the lats pull, not the triceps; deep stretch overhead.',
    primaryMuscles: [MuscleSlug.LATS],
    secondaryMuscles: [MuscleSlug.TRICEPS],
    equipment: [EquipmentSlug.BARBELL, EquipmentSlug.FLAT_BENCH],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'barbell-skull-crusher',
    modality: 'barbell',
    family: 'elbow-extension-press',
    name: 'Barbell Skull Crusher',
    category: 'Arms',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Bar past the forehead — the pressing-family barbell tricep extension.',
    instructions: 'Lie on a bench, bar above the chest. Bend the elbows to lower the bar past the forehead, extend back up.',
    tips: 'Upper arms stay vertical; lower slow — the name is instructions enough.',
    primaryMuscles: [MuscleSlug.TRICEPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.BARBELL, EquipmentSlug.FLAT_BENCH],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'cable-tricep-pushdown',
    modality: 'cable',
    family: 'elbow-extension-press',
    name: 'Cable Tricep Pushdown',
    category: 'Arms',
    exerciseType: 'cable',
    difficultyLevel: 'beginner',
    description: 'Rope or bar from a high pulley — the pressing-family cable tricep standard.',
    instructions: 'Face a high pulley, elbows pinned. Extend down to full lockout, let it return under control.',
    tips: 'Spread the rope at the bottom; shoulders stay out of it.',
    primaryMuscles: [MuscleSlug.TRICEPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.CABLE_ROPE],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'one-arm-dumbbell-row',
    modality: 'dumbbell',
    family: 'horizontal-pull',
    name: 'One-Arm Dumbbell Row',
    category: 'Back',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'One hand on the bench, one dumbbell — the horizontal-pull dumbbell option.',
    instructions: 'Bracket on a bench, dumbbell in the free hand. Row to the hip, lower fully.',
    tips: 'Pull with the elbow past the ribs; no torso twist.',
    primaryMuscles: [MuscleSlug.LATS],
    secondaryMuscles: [MuscleSlug.UPPER_BACK, MuscleSlug.BICEPS],
    equipment: [EquipmentSlug.DUMBBELL, EquipmentSlug.FLAT_BENCH],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'inverted-row',
    modality: 'machine',
    family: 'horizontal-pull',
    name: 'Inverted Row',
    category: 'Back',
    exerciseType: 'calisthenic',
    difficultyLevel: 'intermediate',
    description: 'Under a bar, row your chest to it — the bodyweight horizontal pull.',
    instructions: 'Hang under a low bar, body straight. Pull the chest to the bar, lower with control.',
    tips: 'Walk the feet out to load it up; the body stays one plank the whole set.',
    primaryMuscles: [MuscleSlug.UPPER_BACK],
    secondaryMuscles: [MuscleSlug.LATS, MuscleSlug.BICEPS],
    equipment: [EquipmentSlug.PULL_UP_BAR],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'wide-grip-cable-row',
    modality: 'cable',
    family: 'horizontal-pull',
    name: 'Wide-Grip Cable Row',
    category: 'Back',
    exerciseType: 'cable',
    difficultyLevel: 'beginner',
    description: 'The cable row on a long bar, elbows flared — upper-back biased rowing variety.',
    instructions: 'Seated at the low pulley with a long bar, grip wide. Row to the chest with elbows high, lower slowly.',
    tips: 'Elbows out, chest tall; squeeze the shoulder blades together at the top.',
    primaryMuscles: [MuscleSlug.UPPER_BACK],
    secondaryMuscles: [MuscleSlug.LATS, MuscleSlug.BICEPS],
    equipment: [EquipmentSlug.CABLE_STRAIGHT_BAR],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'chest-supported-dumbbell-row',
    modality: 'dumbbell',
    family: 'horizontal-pull',
    name: 'Chest-Supported Dumbbell Row',
    category: 'Back',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'Prone on an incline bench — rowing with the lower back fully out of it.',
    instructions: 'Chest on an incline bench, dumbbells hanging. Row both to the ribs, lower under control.',
    tips: 'The bench holds the line — no torso English possible; pause at the top.',
    primaryMuscles: [MuscleSlug.LATS],
    secondaryMuscles: [MuscleSlug.UPPER_BACK, MuscleSlug.BICEPS],
    equipment: [EquipmentSlug.DUMBBELL, EquipmentSlug.INCLINE_BENCH],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'ez-bar-curl',
    modality: 'barbell',
    family: 'elbow-flexion',
    name: 'EZ-Bar Curl',
    category: 'Arms',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'The angled bar — barbell loading with a wrist-friendlier grip.',
    instructions: 'EZ bar at arms\u2019 length, semi-supinated grip. Curl to the shoulders, lower fully.',
    tips: 'The angled grip shifts some load to the brachialis; same no-swing rule as the straight bar.',
    primaryMuscles: [MuscleSlug.BICEPS],
    secondaryMuscles: [MuscleSlug.FOREARMS],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'flat-barbell-bench-press',
    modality: 'barbell',
    family: 'chest-press',
    name: 'Flat Barbell Bench Press',
    category: 'Chest',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'The flat barbell bench — the pressing fundamental every gym knows.',
    instructions: 'Lie flat, bar over the chest. Lower to the chest, press to lockout.',
    tips: 'Shoulder blades pinned; bar path a shallow J; feet drive the floor.',
    primaryMuscles: [MuscleSlug.CHEST],
    secondaryMuscles: [MuscleSlug.FRONT_DELTS, MuscleSlug.TRICEPS],
    equipment: [EquipmentSlug.BARBELL, EquipmentSlug.FLAT_BENCH],
    defaultSets: 3,
    defaultReps: [6, 10],
  },
  {
    slug: 'flat-dumbbell-bench-press',
    modality: 'dumbbell',
    family: 'chest-press',
    name: 'Flat Dumbbell Bench Press',
    category: 'Chest',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'Flat pressing with dumbbells — deeper stretch, each side honest.',
    instructions: 'Dumbbells over the chest. Lower until the elbows pass the torso, press together.',
    tips: 'No clanging the bells at the top; control the bottom inch.',
    primaryMuscles: [MuscleSlug.CHEST],
    secondaryMuscles: [MuscleSlug.FRONT_DELTS, MuscleSlug.TRICEPS],
    equipment: [EquipmentSlug.DUMBBELL, EquipmentSlug.FLAT_BENCH],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'machine-chest-press',
    modality: 'machine',
    family: 'chest-press',
    name: 'Machine Chest Press',
    category: 'Chest',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description: 'The seated chest press — fixed path pressing for the flat-press role.',
    instructions: 'Set the seat so handles sit mid-chest. Press to lockout, return under control.',
    tips: 'Full stack travel; the machine owns the path so own the tempo.',
    primaryMuscles: [MuscleSlug.CHEST],
    secondaryMuscles: [MuscleSlug.TRICEPS],
    equipment: [EquipmentSlug.CHEST_PRESS_MACHINE],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 't-bar-row',
    modality: 'barbell',
    family: 'horizontal-pull',
    name: 'T-Bar Row',
    category: 'Back',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Bar in the landfloor groove, chest angled — the supported heavy row.',
    instructions: 'Straddle the bar, hinge to ~45°. Row to the chest, lower fully.',
    tips: 'Chest stays tall; squeeze at the top; no hitching with the hips.',
    primaryMuscles: [MuscleSlug.LATS],
    secondaryMuscles: [MuscleSlug.UPPER_BACK, MuscleSlug.BICEPS],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'machine-seated-row',
    modality: 'machine',
    family: 'horizontal-pull',
    name: 'Machine Seated Row',
    category: 'Back',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description: 'The plate-loaded seated row — the machine row.',
    instructions: 'Chest against the pad, handles out. Row to the torso, return slowly.',
    tips: 'Let the shoulders walk forward at full stretch; row from there.',
    primaryMuscles: [MuscleSlug.LATS],
    secondaryMuscles: [MuscleSlug.UPPER_BACK, MuscleSlug.BICEPS],
    equipment: [EquipmentSlug.SEATED_ROW_MACHINE],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'chin-up',
    modality: 'machine',
    family: 'vertical-pull',
    name: 'Chin-Up',
    category: 'Back',
    exerciseType: 'calisthenic',
    difficultyLevel: 'intermediate',
    description: 'Underhand grip, chin over the bar — the biceps-heavy vertical pull.',
    instructions: 'Hang with an underhand grip. Pull until the chin clears, lower fully.',
    tips: 'Chest to the bar beats chin-grazing; per-set quality over kipping.',
    primaryMuscles: [MuscleSlug.LATS],
    secondaryMuscles: [MuscleSlug.BICEPS],
    equipment: [EquipmentSlug.PULL_UP_BAR],
    defaultSets: 3,
    defaultReps: [6, 10],
  },
  {
    slug: 'arnold-press',
    modality: 'dumbbell',
    family: 'overhead-press',
    name: 'Arnold Press',
    category: 'Shoulders',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Palms rotate as you press — the overhead press with a twist.',
    instructions: 'Start palms-in at the chest. Press up while rotating to palms-forward, reverse down.',
    tips: 'The rotation is the rep — own it both directions.',
    primaryMuscles: [MuscleSlug.FRONT_DELTS],
    secondaryMuscles: [MuscleSlug.SIDE_DELTS],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'machine-lateral-raise',
    modality: 'machine',
    family: 'lateral-raise',
    name: 'Machine Lateral Raise',
    category: 'Shoulders',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description: 'Pads or handles at the elbows — the machine side-delt raise.',
    instructions: 'Set the seat so pads sit at the elbow line. Raise to shoulder height, lower slowly.',
    tips: 'Machine owns the path; make the top squeeze the rep.',
    primaryMuscles: [MuscleSlug.SIDE_DELTS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.CABLE_HANDLE],
    defaultSets: 3,
    defaultReps: [12, 15],
  },
  {
    slug: 'band-face-pull',
    modality: 'floor',
    family: 'face-pull',
    name: 'Band Face Pull',
    category: 'Shoulders',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description: 'A band anchored high — the anywhere face pull.',
    instructions: 'Anchor a band at head height. Pull to the face, elbows high, rotate outward.',
    tips: 'Thumbs back at the finish; slow returns beat heavy bands.',
    primaryMuscles: [MuscleSlug.REAR_DELTS],
    secondaryMuscles: [MuscleSlug.UPPER_BACK],
    equipment: [EquipmentSlug.RESISTANCE_BAND],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'hammer-curl',
    modality: 'dumbbell',
    family: 'elbow-flexion',
    name: 'Hammer Curl',
    category: 'Arms',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'Neutral grip, hammer the weight up — the brachialis curl.',
    instructions: 'Dumbbells at the sides, palms facing in. Curl to the shoulders, lower fully.',
    tips: 'The grip never rotates; the forearm stays plank-still.',
    primaryMuscles: [MuscleSlug.BICEPS],
    secondaryMuscles: [MuscleSlug.FOREARMS],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'preacher-curl-machine',
    modality: 'machine',
    family: 'elbow-flexion',
    name: 'Preacher Curl Machine',
    category: 'Arms',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description: 'The angled pad takes the swing out — the preacher machine curl.',
    instructions: 'Arms on the pad, grips shoulder-width. Curl up, lower to full extension.',
    tips: 'Full stretch at the bottom is the growth half; no partial cheat.',
    primaryMuscles: [MuscleSlug.BICEPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.CABLE_HANDLE],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'concentration-curl',
    modality: 'dumbbell',
    family: 'elbow-flexion',
    name: 'Concentration Curl',
    category: 'Arms',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'Seated, elbow braced on the thigh — the pure single-arm curl.',
    instructions: 'Sit, brace the working elbow inside the thigh. Curl to the shoulder, lower slowly.',
    tips: 'One arm, zero body English; the brace is the point.',
    primaryMuscles: [MuscleSlug.BICEPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'close-grip-bench-press',
    modality: 'barbell',
    family: 'elbow-extension-press',
    name: 'Close-Grip Bench Press',
    category: 'Arms',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Bench with a narrow grip — the pressing-family barbell tricep move.',
    instructions: 'Grip just inside shoulder width. Lower to the lower chest, press to lockout.',
    tips: 'Elbows tuck, not flare; lockouts are the triceps talking.',
    primaryMuscles: [MuscleSlug.TRICEPS],
    secondaryMuscles: [MuscleSlug.CHEST],
    equipment: [EquipmentSlug.BARBELL, EquipmentSlug.FLAT_BENCH],
    defaultSets: 3,
    defaultReps: [8, 10],
  },
  {
    slug: 'machine-overhead-tricep-extension',
    modality: 'machine',
    family: 'elbow-extension-overhead',
    name: 'Machine Overhead Tricep Extension',
    category: 'Arms',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description: 'The seated overhead machine — the long-head stretch without a bar.',
    instructions: 'Set the seat, handles overhead. Lower behind the head, extend fully.',
    tips: 'Deep behind-head position; the stretch is the working half.',
    primaryMuscles: [MuscleSlug.TRICEPS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.TRICEP_EXTENSION_MACHINE],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'front-squat',
    modality: 'barbell',
    family: 'knee-dominant-bilateral',
    name: 'Front Squat',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'advanced',
    description: 'Bar in the front rack — the quad-bilateral punisher.',
    instructions: 'Bar on the front delts, elbows high. Squat between the heels, drive up tall.',
    tips: 'Elbows up is the whole lift; the torso stays vertical as a wall.',
    primaryMuscles: [MuscleSlug.QUADS],
    secondaryMuscles: [MuscleSlug.GLUTES, MuscleSlug.ABS],
    equipment: [EquipmentSlug.BARBELL, EquipmentSlug.SQUAT_RACK],
    defaultSets: 3,
    defaultReps: [6, 8],
  },
  {
    slug: 'leg-extension',
    modality: 'machine',
    family: 'knee-dominant-bilateral',
    name: 'Leg Extension',
    category: 'Upper Leg',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description: 'The seated knee extension — quad isolation, machine path.',
    instructions: 'Shins behind the pad. Extend to lockout, lower with resistance.',
    tips: 'One-second squeeze at the top; never let the stack slam.',
    primaryMuscles: [MuscleSlug.QUADS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.LEG_EXTENSION_MACHINE],
    defaultSets: 3,
    defaultReps: [12, 15],
  },
  {
    slug: 'barbell-hip-thrust',
    modality: 'barbell',
    family: 'hip-extension',
    name: 'Barbell Hip Thrust',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'intermediate',
    description: 'Shoulders on the bench, bar on the hips — the glute driver.',
    instructions: 'Upper back on a bench, bar padded at the hips. Drive to full hip extension, lower.',
    tips: 'Chin tucked, ribs down; the top is a squeeze not a arch.',
    primaryMuscles: [MuscleSlug.GLUTES],
    secondaryMuscles: [MuscleSlug.HAMSTRINGS],
    equipment: [EquipmentSlug.BARBELL, EquipmentSlug.FLAT_BENCH],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'glute-bridge',
    modality: 'floor',
    family: 'hip-extension',
    name: 'Glute Bridge',
    category: 'Upper Leg',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description: 'The floor hip extension — glutes with zero equipment.',
    instructions: 'Lie back, knees bent. Drive the hips to the ceiling, squeeze, lower.',
    tips: 'Pause at the top; the hips finish the rep, not the lower back.',
    primaryMuscles: [MuscleSlug.GLUTES],
    secondaryMuscles: [MuscleSlug.HAMSTRINGS],
    equipment: [EquipmentSlug.FLOOR_SPACE],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'dumbbell-step-up',
    modality: 'dumbbell',
    family: 'knee-dominant-unilateral',
    name: 'Dumbbell Step-Up',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'beginner',
    description: 'Onto a box, one leg drives — the honest unilateral press.',
    instructions: 'Dumbbells at the sides, one foot on a box. Drive through the top leg to stand, lower slowly.',
    tips: 'The low leg never pushes; per-leg — match reps both sides.',
    primaryMuscles: [MuscleSlug.QUADS],
    secondaryMuscles: [MuscleSlug.GLUTES],
    equipment: [EquipmentSlug.DUMBBELL],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'barbell-deadlift',
    modality: 'barbell',
    family: 'hip-hinge-spinal-extension',
    name: 'Barbell Deadlift',
    category: 'Upper Leg',
    exerciseType: 'free_weight',
    difficultyLevel: 'advanced',
    description: 'The conventional deadlift — the hip hinge with a barbell on the floor.',
    instructions: 'Bar over mid-foot, hinge and grip, brace. Stand with the bar dragging the legs, return under control.',
    tips: 'Push the floor away; the bar never leaves the legs; brace like a squat.',
    primaryMuscles: [MuscleSlug.HAMSTRINGS],
    secondaryMuscles: [MuscleSlug.GLUTES, MuscleSlug.LOWER_BACK],
    equipment: [EquipmentSlug.BARBELL],
    defaultSets: 3,
    defaultReps: [5, 8],
  },
  {
    slug: 'machine-back-extension',
    modality: 'machine',
    family: 'hip-hinge-spinal-extension',
    name: 'Machine Back Extension',
    category: 'Upper Leg',
    exerciseType: 'machine',
    difficultyLevel: 'beginner',
    description: 'The 45° station — spinal extension with load support.',
    instructions: 'Pad at the hip crease, feet anchored. Hinge down, raise to a straight line.',
    tips: 'Stop at neutral — no hyperextension; hands cross the chest.',
    primaryMuscles: [MuscleSlug.LOWER_BACK],
    secondaryMuscles: [MuscleSlug.GLUTES, MuscleSlug.HAMSTRINGS],
    equipment: [EquipmentSlug.BACK_EXTENSION_STATION],
    defaultSets: 3,
    defaultReps: [10, 12],
  },
  {
    slug: 'band-tibia-raise',
    modality: 'floor',
    family: 'dorsi-flexion',
    name: 'Band Tibia Raise',
    category: 'Lower Leg',
    exerciseType: 'calisthenic',
    difficultyLevel: 'beginner',
    description: 'A band around the forefoot — the anywhere tibia raise.',
    instructions: 'Sit, band looped over the forefoot. Pull the toes toward the shin against the band.',
    tips: 'Slow up, slower down; the shin muscle only knows tension.',
    primaryMuscles: [MuscleSlug.TIBIALIS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.RESISTANCE_BAND],
    defaultSets: 3,
    defaultReps: [15, 20],
  },
  {
    slug: 'ab-wheel-rollout',
    modality: 'floor',
    family: 'trunk-flexion',
    name: 'Ab Wheel Rollout',
    category: 'Abs',
    exerciseType: 'calisthenic',
    difficultyLevel: 'advanced',
    description: 'The wheel rollout — trunk flexion under full-body tension.',
    instructions: 'Kneel with the wheel, arms extended. Roll out as far as the trunk holds, pull back.',
    tips: 'Never let the hips sag; shorter reps with a rigid trunk beat longer sloppy ones.',
    primaryMuscles: [MuscleSlug.ABS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.FLOOR_SPACE],
    defaultSets: 3,
    defaultReps: [8, 12],
  },
  {
    slug: 'hanging-knee-raise',
    modality: 'machine',
    family: 'vertical-leg-raise',
    name: 'Hanging Knee Raise',
    category: 'Abs',
    exerciseType: 'calisthenic',
    difficultyLevel: 'intermediate',
    description: 'Hanging from the bar, knees to chest — the vertical leg raise.',
    instructions: 'Hang from a bar. Curl the knees to the chest, lower without swinging.',
    tips: 'Curl the pelvis, don\u2019t just lift the knees; a controlled lower kills the swing.',
    primaryMuscles: [MuscleSlug.LOWER_ABS],
    secondaryMuscles: [],
    equipment: [EquipmentSlug.PULL_UP_BAR],
    defaultSets: 3,
    defaultReps: [10, 15],
  },

];

// ──────────────────────────────────────────────────────────────────────
// Lookup helpers
// ──────────────────────────────────────────────────────────────────────

/** Indexes the system exercises by slug for O(1) lookup. */
export const SYSTEM_EXERCISES_BY_SLUG: Record<string, SystemExerciseData> =
  Object.fromEntries(SYSTEM_EXERCISES.map((e) => [e.slug, e]));

/** Returns the system exercise data for a given slug, or undefined. */
export function getSystemExercise(slug: string): SystemExerciseData | undefined {
  return SYSTEM_EXERCISES_BY_SLUG[slug];
}

// ──────────────────────────────────────────────────────────────────────
// Attribute formatting (slugs → display strings)
// ──────────────────────────────────────────────────────────────────────

/**
 * Normalizes the equipment field (which can be a slug or an isRequired
 * object) to just the slug.
 */
function equipmentSlugOf(
  entry: EquipmentSlug | { slug: EquipmentSlug; isRequired: boolean },
): EquipmentSlug {
  return typeof entry === 'string' ? entry : entry.slug;
}

export interface ExerciseAttributeLabels {
  /** Comma-joined equipment display names, e.g. "Barbell, Incline Bench". */
  equipmentLabel: string;
  /** Comma-joined primary muscle display names, e.g. "Upper Chest, Front Delts". */
  primaryMuscleLabel: string;
  /** Comma-joined secondary muscle display names (empty string if none). */
  secondaryMuscleLabel: string;
}

/**
 * Resolves a SystemExerciseData's muscle/equipment slugs into
 * human-readable display strings for chip-style attribute rendering.
 * Used by the split preview + active-session surfaces where we want to
 * show attribute context inline without a DB join round-trip.
 */
export function formatExerciseAttributes(
  exercise: SystemExerciseData,
): ExerciseAttributeLabels {
  const equipmentLabel = exercise.equipment
    .map(equipmentSlugOf)
    .map((s) => EQUIPMENT_DISPLAY_NAMES[s] ?? s)
    .join(', ');
  const primaryMuscleLabel = exercise.primaryMuscles
    .map((s) => MUSCLE_DISPLAY_NAMES[s] ?? s)
    .join(', ');
  const secondaryMuscleLabel = exercise.secondaryMuscles
    .map((s) => MUSCLE_DISPLAY_NAMES[s] ?? s)
    .join(', ');
  return { equipmentLabel, primaryMuscleLabel, secondaryMuscleLabel };
}

/** Formats a [min, max] rep range as "min-max" (or '—' if missing). */
export function formatRepRange(reps: [number, number] | null | undefined): string {
  if (!reps || reps.length !== 2) return '—';
  const [min, max] = reps;
  if (min === max) return String(min);
  return `${min}-${max}`;
}
